nats.go
Order of nc.Opts.Servers would remain the same if use math.rand without a seed,
so use time.UnixNano() as seed to init it.
=> fix mrand not init properly

conn_test.go, nats.go
Makes the client proactively follow the `MaxPayload` size which was announced by the server upon connect. After this change, the client would get an `ErrMaxPayload` error when trying to publish a message which is larger than this limit.
=> Enforce MaxPayload on the client

nats.go
In order to improve chances that there is not a race in this step.
/cc @derekcollison @kozlovic 
```
WARNING: DATA RACE
Read by goroutine 228:
github.com/nats-io/nats.TestServerAutoUnsub()
.../src/github.com/nats-io/nats/sub_test.go:28 +0x3cc
testing.tRunner()
.../src/go/src/testing/testing.go:447 +0x133
Previous write by goroutine 256:
github.com/nats-io/nats.func·077()
.../src/github.com/nats-io/nats/sub_test.go:17 +0x50
github.com/nats-io/nats.(*Conn).deliverMsgs()
.../src/github.com/nats-io/nats/nats.go:988 +0x214
Goroutine 228 (running) created at:
testing.RunTests()
.../src/go/src/testing/testing.go:555 +0xd4e
testing.(*M).Run()
.../src/go/src/testing/testing.go:485 +0xe0
main.main()
github.com/nats-io/nats/_test/_testmain.go:266 +0x28c
Goroutine 256 (running) created at: …
```
=> Atomically load delivered messages accounted value before on compare.

nats.go
Even all `kickFlusher()` is under `nc.mu.Lock()`, but I think use select just a better way :)
=> chan op in kickflusher is not atomic

nats.go
When connecting to a server with incorrect user name and/or password the server sends an error message. When processing this error, we should close the connection without invoking the callbacks.
=> Fix behavior of connect on Authentication failure

nats.go, test/reconnect_test.go
When a disconnect occurs, the flusher will exit but there may be still multiple calls to kickFlusher() that would cause the flush channel to be full (created buffered with length 1024). When that occurs and spinUpSocketWatchers starts and calls waitForExits, the call to nc.fch <- true would block because the channel is full and nothing is empting it. That would cause the reconnect process to "fail" blocking in spinUpSocketWatchers.
=> Fix waitForExits blocking when flush channel is full

test/reconnect_test.go
This test was created for PR https://github.com/nats-io/nats/pull/85
Forgot to shutdown the server at the end of that test, which would prevent new tests after this one to run properly when using server on port 222222
=> Fix test TestFullFlushChanDuringReconnect

nats.go, test/conn_test.go
We have some messages that might be quite large.  Publishing any of these causes the connection to never send a message again, because publish() checks nc.err != nil and then bails.  ErrMaxPayload is only relevant to the individual message, it shouldn't make the whole connection bad.
=> Don't fail to publish subsequent messages after sending one that's too big

natspkg_test.go, test/basic_test.go, test/reconnect_test.go, test/sub_test.go
* Some tests would fail with GOMAXPROCS=1 in that the SubChanLen would not get a chance to be full
* Got a RACE report when manipulating nc.ps from the test code
=> Fix some tests for RACE and with GOMAXPROCS=1

nats.go, test/cluster_test.go, test/reconnect_test.go, test/sub_test.go, test/test.go
I think that those changes may help prevent random build failures on Travis. Note that the change to the test's Wait() function is something to keep in mind when writing new tests, if those tests rely on Wait() to timeout quickly. You should then use the WaitTime() version that allows you to set a small timeout.
cc @derekcollison
=> Change default wait for tests

nats.go, test/auth_test.go, test/netchan_test.go, test/reconnect_test.go, test/sub_test.go
This is changing the behavior of the connect and reconnect mechanism to do things synchronously, under the session lock. This would solve issues #68 and #87.
=> "Synchronous" connect and reconnect

examples/nats-pub.go
* I removed the -t (not used in the publish example)
* I added the print of the nats.DefaultURL to clarify server spec.
=> Updated the usage statment to remove unneeded arg.

examples/nats-qsub.go, examples/nats-req.go, examples/nats-rply.go
Created a nats-qsub.go example. Main difference from nats-sub.go is that I called QueueSubscribe and printed out the queue name as well as the pid of the executable in the printMsg function for demonstration purposes otherwise it's identical to nats-sub.go
Changes:
*Second argument is queue name. 
*Subscribe call is to QueueSubscribe
*printMsg prints 2 additional pieces of information. queue name and process id.
=> Added a queueing subscriber to the example programs

encoders/builtin/gob_test.go, encoders/builtin/json_test.go, encoders/protobuf/protobuf_test.go, test/test.go
```
$ go test -bench=. -benchmem github.com/nats-io/nats/encoders/{builtin,protobuf}
PASS
BenchmarkGobMarshalStruct-4 	   20000	     67841 ns/op	    9431 B/op	     204 allocs/op
BenchmarkJsonMarshalStruct-4	   50000	     23620 ns/op	    2531 B/op	      41 allocs/op
ok  	github.com/nats-io/nats/encoders/builtin	3.863s
PASS
BenchmarkProtobuf-4	  100000	     16275 ns/op	    1866 B/op	      46 allocs/op
ok  	github.com/nats-io/nats/encoders/protobuf	1.869s
```
=> Added benchmarks for encoding, structs only.

nats.go
In working on the clients we found this wasn't being used.
=> Remove the unused function resetPendingFlush().

nats.go
atomic.* functions crash on 32bit systems (i386, armhf) if the value is not 64bit aligned. Despite the comment in the code, Conn.ssid is not aligned correctly and crash on armhf. 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x4 pc=0x15ef18]
goroutine 1 [running]:
sync/atomic.addUint64(0x1053cef4, 0x1, 0x0, 0x1, 0x0)
/usr/lib/go/src/sync/atomic/64bit_arm.go:31 +0x70
github.com/nats-io/nats.(*Conn).subscribe(0x1053ce00, 0x260248, 0x5, 0x0, 0x0, 0x10537340, 0x10000, 0x0, 0x0, 0x0)
/home/domain/longsleep/go/src/github.com/nats-io/nats/nats.go:1372 +0x300
github.com/nats-io/nats.(*EncodedConn).subscribe(0x1052e6b0, 0x260248, 0x5, 0x0, 0x0, 0x2050a0, 0x1050a3b8, 0x234088, 0x0, 0x0) …
```
=> Fix 64bit alignment of Conn.ssid, to avoid crash

nats.go
The affected lines set nc.err, but the calling function immediately reassigns nc.err, rendering these statements useless.
=> Removed ineffective nc.err settings

nats.go, test/conn_test.go, test/reconnect_test.go
* Since the (re)connect process was made synchronous, we now need to handle the possible return of +OK by the server.
=> Fix handling of Verbose option during connect/reconnect

nats.go
This code was copied from some TLS changes into refactoring of connect to make it synchronous. This test does not make sense in that context. If there is low level TLS errors during the processing of the connect protocol, calls to buffer write/read would return the appropriate error.
=> Remove incorrect TLS error check in sendConnect

README.md, enc.go, examples/nats-bench.go, nats.go, nats_test.go, netchan.go, scripts/cov.sh, test/bench_test.go, test/cluster_test.go, test/reconnect_test.go, test/sub_test.go
This PR removes channels for async subscribers, #115 , cleans up #104 by adding  ChanSubscribe(), and addresses #86. Also cleans up handling of SlowConsumers.
=> Remove Channels

parser.go
I was looking at the test coverage and this caught my eye.
=> parser: rm unused OP_CONNECT & CONNECT_ARG.

enc.go, enc_test.go, encoders/builtin/json_test.go
This issue was discussed in https://github.com/nats-io/nats/issues/78
I create test cases to reproduce errors
You can checkout this commit with failed tests https://github.com/AnatoliiPrylutskyi/nats/commit/3d9148470958d898ffa705cee5894a018c8f7d29
Also I remove global errors in places where it cause errors. All tests are green.
=> Fix error in next message after encode/decode fail in previous

nats.go
Addresses issue #136.
This also could be addressed by moving creation of pending buffer in `processOpErr`?
=> Fix possible nil dereference when publish during reconnect.

nats_test.go, parser.go
Adding tests for code coverage, I discovered that we would not check for missing sid (sid would be -1 due to parseInt64). I believe sid is mandatory.
=> Fix parser to check for missing sid.

enc.go, enc_test.go, encoders/builtin/enc_test.go, netchan.go, test/netchan_test.go
- Return error when Handler has no argument (would cause nil pointer panic)
- Schedule async error callbacks when possible
- Add more tests and increase test coverage
=> Fix some encoders issues.

nats.go, nats_test.go
The case of the error message was changed to all lower case in the client. The server is using mixed case. This would cause the check to fail, resulting in connection close, instead of possibly trying to reconnect.
=> Fix "Stale Connection" error check.

nats.go, test/sub_test.go
- Calls to NextMsg() for SyncSubscriptions may block until Timeout even when max messages have been received and subscription is removed.
- During reconnect, when resending the subscriptions, update the 'max' value with 'max - delivered' to prevent server for sending messages for nothing.
=> Fix for issues #151 & #152.

nats.go, nats_test.go, test/basic_test.go, test/conn_test.go, test/sub_test.go
- If nc.Flush[Timeout]() was waiting for a response and the connection would close, nc.Flush() would return without error. This is not appropriate. It will now return ErrConnectionClosed.
- Adding/Updating several tests for more code coverage.
=> Fix nc.Flush() on connection close + much more code coverage.

nats.go, test/basic_test.go, test/conn_test.go, test/sub_test.go
- Revisited the use of nc.err to limit it to report async errors.
- Publish and Flush calls will no longer fail if an asyn error occurs
- Flush will report an error if connection is closed/lost during flush
- Flush calls are failed during a reconnect
- Tests updated
=> Fix Publish and Flush calls to not fail on async error (slow consumer)

encoders/protobuf/protobuf_enc.go, encoders/protobuf/protobuf_test.go
Hi
I found it convenient and intuitive to subscribe with empty interface{} in case when you don't need arguments to reply with encoded response. Also it's convenient to request with nil argument.
I used this modified proto encoder for our application.
I create failed test cases in commit: https://github.com/AnatoliiPrylutskyi/nats/commit/a3c60694003763933585705ca6f89b18599a8367
Thanks
=> Protobuf encoder improvement

nats.go, test/cluster_test.go
See rationale in #164. We should not reset the number of reconnects for a given server record until after the server accepts our CONNECT protocol message. 
/cc @nats-io/dev
=> Move cur.reconnects reset after CONNECT attempt

nats.go, test/bench_test.go
This increased performance by over an order of magnitude and is much more friendly to the entropy pool, especially when using may nats.Request() calls.
=> Use nuid for INBOX suffix

nats.go, test/cluster_test.go, test/reconnect_test.go, test/sub_test.go, test/test.go
The issue manifests on Windows with a ReconnectWait lower than a second, because it takes more than a second for createConn() to return when no server is running. Therefore, the loop would never sleep (and never release the lock), which would prevent a Close() from breaking the reconnect loop.
=> Fixed reconnect loop possibly not yielding to Close()

nats.go, test/basic_test.go
-The dispatcher was started as a go routine before initiating the
connect. However, if we failed to connect, we would never return
a connection, so we would not shutdown this dispatcher since this
was done in Close().
-Added a test which check go routines number before/after a failed
connect.
=> Fixed async callback dispatcher leak on connect failure

nats.go, test/basic_test.go
-The async delivery routine was not signaled on connection close.
-Added tests that verify on unsubscribe and connection close.
=> Fixed leak of async subscription delivery routine on connection close

nats.go, test/sub_test.go
-When creating a Chan subscriber, the user provides the channel.
We should not close that channel on connection close.
-Add test to check that connection close does not close the user
channel.
=> Fixed panic on channel receive after connection closed

nats.go, test/conn_test.go
If one creates a nats.Options struct and does not specify a timeout,
the library would use 0 for the connect timeout which would prevent
the connect to succeed. If timeout is not specify, the default
value (2 seconds) will now be used.
=> Fix use of default connect timeout in opts.Connect()

bench/bench.go, examples/nats-bench.go
Modified nats-bench so that subscribers wait to receive the total message count.
Modified the bench library so that it adds the number of messages that the client received or published.
=> Changes to nats-bench and bench lib

nats.go, nats_test.go, parser.go, test/auth_test.go
This would be used in conjunction with server's PR #314.
The client may receive INFO protocols with a field containing
a possible array of URLs that correspond to server addresses in
the full mesh cluster that clients can connect to.
The server pool is updated with these URLs.
3 new Options and 2 new Options setters have been introduced to
manage username/password and/or tokens when dealing with these
bare URLs.
/cc @derekcollison
=> [ADDED] Support for processing of asynchronous INFO protocols

README.md
In the Clustered Usage section, added a paragraph that explains
the possible need for providing user/pwd/token info to the library.
=> [UPDATED] Readme [ci skip]

nats.go, test/conn_test.go
Exposes `IsConnected` method in the client similarly to `IsReconnecting` and `IsClosed` which are already exposed as well.
=> Add IsConnected method to assert that the client is connected

.travis.yml, nats.go, util/tls.go, util/tls_pre17.go
Running `go vet ./...` with `go 1.7.3` would report the following:
```
nats.go:769: assignment copies lock value to tlsCopy: crypto/tls.Config contains sync.Once contains sync.Mutex
```
Add a “clone” function while waiting for this to be addressed
by the language itself (https://go-review.googlesource.com/#/c/28075/)
=> [FIXED] assignment copies lock value for crypto/tls.Config

nats.go, test/conn_test.go
This adds a customizable `FlusherTimeout` option for the flusher loop to be able to yield after a certain time in case a write to the underlying writer takes too long due to an unhealthy connection.
This prevents the client blocking for an indefinite amount of time until reaching an OS level `i/o timeout` since the `bufio.Flush` is happening while the lock is being hold, thus giving room for the ping interval to be able to `processOpErr` and disconnect once it reaches the max amount of missing ping replies from the server (with an unhealthy connection the reading loop would be stuck on `conn.Read` too because there is no deadline either, so it would take as a long as the ping interval check closes the connection or `i/o timeout`).
=> Add FlusherTimeout to prevent blocking for long on unhealthy connections

.travis.yml, encoders/protobuf/protobuf_enc.go, nats.go, staticcheck.ignore, test/conn_test.go, test/sub_test.go
Added gosimple + update to staticcheck
Based on @y0ssar1an PRs.
- Update go versions to .4
- Get gosimple package
- Updated staticcheck's URL
- Use staticcheck.ignore file for exceptions
- Moved build and staticcheck/gosimple checks in `before_script`
section to fail fast
- Fixed reports from gosimple and staticcheck
=> Add gosimple, update staticcheck and go to .4 releases

nats.go, nats_test.go
When connecting to a server, the received INFO may contain an array
of URLs. The current code was adding those and then shuffeling the
entire pool (if NoRandomize is false). This is wrong since the
connect (and reconnect) loop would then potentially skip never
tried servers and try again servers that had just failed.
=> [FIXED] Do not shuffle entire pool when adding URL from INFO

nats.go, staticcheck.ignore
There have been 2 reports in the last 10 months of this happening
once each. We have not been able to reproduce the issue. However,
this code change should eliminate the possibility of code going
into a Wait() while in parallel doing an Add() (for the same group).
There is no new test since we have multiple tests that check for
reconnect and we have not been able to reproduce. A long running
test causing 100,000 server restarts at random interval has been
running on *original code* without producing the panic.
Attempt to resolve #192
=> [FIXED] Possible panic on WaitGroup.Wait()

test/cluster_test.go, test/conn_test.go, test/reconnect_test.go
Fixes race which occurs in one of the tests
```
=== RUN   TestProperFalloutAfterMaxAttemptsWithAuthMismatch
==================
WARNING: DATA RACE
Read at 0x00c420302da8 by goroutine 55:
runtime.convT2E()
/usr/local/go/src/runtime/iface.go:191 +0x0
github.com/nats-io/go-nats/test.TestProperFalloutAfterMaxAttemptsWithAuthMismatch()
/Users/wally/repos/nats-dev/src/github.com/nats-io/go-nats/test/cluster_test.go:465 +0x96b
testing.tRunner()
/usr/local/go/src/testing/testing.go:657 +0x107
Previous write at 0x00c420302da8 by goroutine 54:
github.com/nats-io/go-nats.(*Conn).doReconnect()
/Users/wally/repos/nats-dev/src/github.com/nats-io/go-nats/nats.go:1311 +0x3da
Goroutine 55 (running) created at:
testing.(*T).Run()
/usr/local/go/src/testing/testing.go:697 +0x543
testing.runTests.func1() …
```
=> Fix data race in cluster test

nats.go, test/sub_test.go
Use 2 connections to avoid server cutting of the connection due
to slow consumer, which can happen if client's flusher is blocked
trying to send messages to server while server is blocked trying
to send messages to client (client readloop wants the lock that
flusher has).
=> Fixed flapping test

nats.go, test/conn_test.go
If `DiscoveredServersCB` is set, the client library will invoke this
callback when it is notified by the server it connects to that
a new server has joined the cluster. This callback is not invoked
in the initial `Connect()`. A ConnHandler is used. The user can
invoke `nc.DiscoveredServers()` to get the list of discovered servers.
But in some cases, it is just enough to know that a new server
has joined. A use case is in NATS Streaming server with the
channels partitioning/sharding feature where a server needs to know
if the cluster has changed in which case it should resend its list
of channels.
=> [ADDED] Handler invoked when a new server joins the NATS Cluster

context.go, nats.go, staticcheck.ignore, test/context_test.go
Adds `context.Context` support to the +Go1.7 clients implementing the APIs suggested at https://github.com/nats-io/go-nats/issues/221#issuecomment-288193653
```go
func (c *EncodedConn) RequestWithContext(ctx context.Context, subject string, v interface{}, vPtr interface{}) error
func (nc *Conn) RequestWithContext(ctx context.Context, subj string, data []byte) (*Msg, error)
func (s *Subscription) NextMsgWithContext(ctx context.Context) (*Msg, error)
```
Fixes #221
=> [ADDED] context.Context support

nats.go, test/auth_test.go
Connection locking was missing in processPermissionsViolation().
Added a test that verifies that async cb error is invoked on
invalid publish or subscribe, and that the connection is not
closed neither by the server nor client.
@derekcollison Opening this for discussion: was it the proper intent for the server to keep the client connection (not closing it at the moment)? If so, then it makes sense for the client also to not close it and treat this as a non fatal error. This PR then simply fixes the locking and add a test (coverage was non existent for this function).
=> [FIXED] Locking in processPermissionsViolation() and added test

.travis.yml, context.go, nats.go, test/basic_test.go, test/bench_test.go, test/context_test.go
This request pattern is sematically the same but utilizes a single
wildcard subscription and the last token context for the response
subject binding to each request. Since NATS floods interest (subscriptions),
the old requestor pattern would create a new inbox subscription for each request.
It would then auto-unsubscribe and delete the subscription after the
response was received, causing quite a bit of protocol traffic.
So although this does have a performance gain as can be seen in the benchmarks,
it's implementation is specifically designed to be more friendly for NATS
clusters.
=> More protocol friendly request pattern. Fix for #294.

nats.go, timer.go, timer_test.go
Requests are somewhat allocation heavy. This should help a bit. Also has a small positive effect on requests performance (more for the old request style).
Benchstat (base 9147cfac69833916f9c73353ba43f939815c330a):
```
name                              old time/op    new time/op    delta
Request-8                           43.9µs ± 5%    43.4µs ± 1%     ~     (p=0.690 n=5+5)
OldRequest-8                        60.0µs ± 3%    57.5µs ± 2%   -4.30%  (p=0.008 n=5+5)
name                              old alloc/op   new alloc/op   delta
Request-8                             885B ± 0%      693B ± 0%  -21.71%  (p=0.008 n=5+5)
OldRequest-8                        2.63kB ± 0%    2.44kB ± 0%   -7.27%  (p=0.000 n=5+4)
name                              old allocs/op  new allocs/op  delta
Request-8 …
```
=> Pool timers to avoid allocations

context.go, nats.go
The new request style was leaking channels in the respMap when requests
timed out. Now we remove them from the map when the request times out.
This also simplifies the respMux setup and prevents multiple resp
subscriptions from being created on the server.
@nats-io/core
=> Fix new-style request leak

nats.go, nats_test.go
Once we introduce config reload support for users, it's possible for a
user to be disconnected due to a change in credentials. Before the user
is disconnected, the server sends an authorization error. We should
allow the user to handle this error in the async error callback.
@nats-io/core
=> Allow handling of authorization errors from the server

nats.go
Similar to https://github.com/nats-io/go-nats/pull/304 this also changes to use zero size empty struct for signaling in the pending pongs channel.
=> Switch to use empty struct for signaling in pongs channel

examples/nats-bench.go, nats.go, nats_test.go, test/auth_test.go, test/basic_test.go, test/cluster_test.go, test/conn_test.go, test/reconnect_test.go, test/sub_test.go
At the moment DefaultOptions is a global struct that is being copied by value. Some of the fields are pointers, so they got copied as well while retaining their value and thus making these fields effectively global. This breaks logic of multiple operations with DefaultOptions which may be modified by other users (e.g. in tests).
This PR is making it a function that returns a fresh copy of DefaultOptions each time to use independently.
=> Make DefaultOptions a function that produces new Options on every call

nats.go, test/conn_test.go
(Follow up from PR: https://github.com/nats-io/go-nats/pull/308)
As part of commit (https://github.com/nats-io/go-nats/commit/c46810140b837ae134c6f47930ea7226691c77b4) it was added the option to be able to set a custom [Dialer](https://golang.org/pkg/net/#Dialer) on the client, but it was also included a default one as part of `nats.DefaultOptions` which was not necessary since one would have been created on connect if it was not set anyway: https://github.com/nats-io/go-nats/blob/7488b993f3f8b09249686708910f052694ef0a5a/nats.go#L683-L688
This removes `Dialer` from being part of the `nats.DefaultOptions` to only leave constants which can't be changed as part of the options, in order to prevent multiple connections sharing the same dialer because of borrowing the same one via the …
=> [REMOVED] Dialer from DefaultOptions

.travis.yml
Travis.CI support `x`  in place of the minor to use the latest for a given major version - https://docs.travis-ci.com/user/languages/go/#Specifying-a-Go-version-to-use
=> Use the latest version of Go in Travis.CI

nats.go
No performance change, but avoids one allocation when (un)subscribing.
```
name                              old alloc/op   new alloc/op   delta
PublishSpeed-8                       0.00B          0.00B          ~     (all equal)
PubSubSpeed-8                         122B ± 0%      121B ± 0%   -1.14%  (p=0.000 n=5+4)
AsyncSubscriptionCreationSpeed-8    1.02kB ±28%    1.00kB ±28%     ~     (p=0.643 n=5+5)
SyncSubscriptionCreationSpeed-8     66.3kB ± 0%    66.3kB ± 0%   -0.02%  (p=0.008 n=5+5)
InboxCreation-8                      64.0B ± 0%     64.0B ± 0%     ~     (all equal)
Request-8                             693B ± 0%      693B ± 0%     ~     (p=1.000 n=4+5)
OldRequest-8                        2.44kB ± 0%    2.37kB ± 0%   -2.63%  (p=0.029 n=4+4)
PublishGobStruct-8 …
```
=> Use Fprintf instead of Sprintf+WriteString

nats.go
Removed nats RootCAs redundant type conversion of rootPEM. ioutil.ReadFile returns []byte, and err. There is no need to typecast rootPEM to []byte since it's already in bytes if there is no error. 
Fixed typo in nats setupServerPool method description
Fixed nats connect comment word spacing.
=> Removed nats RootCAs redundant type conversion of rootPEM and fixed typo 

nats.go, test/auth_test.go
The issue was that we were using `nc.err` as a parameter of
the closure function sent to `nc.ach`. The value of the error
would then change and be whatever last value is.
We now create an error so that this is unique per scheduled
async error.
Updated the test that checks not only that we get the permission
violation error, but that we get the expected one (one for sub
and for for pub).
Resolves #325
=> [FIXED] ErrorHandler not always reporting proper error

nats.go
If when the client issues a Flush() or FlushTimeout(), the client
library times out when at the same time it receives the PONG, there
is a possibility that the processing of the PONG gets the channel
it needs to notify from the array while the routine waiting on
that notification is done waiting but has not yet removed the
channel from the array. This will lead to processPong() to be
stuck in a chan send, which is blocking the readLopp, which will
ultimately lead to server closing this connection.
The solution is to create a buffererd channel (of size 1). We
should not simply do a `select` when trying to notify because we
don't want to miss the notification if the routine sending the PING
is not yet in the select to consume the notification.
Resolves #321
=> [FIXED] Repeated timeout of Flush/FlushTimeout and inability to dispatch

nats.go, test/conn_test.go
We recently added a Dialer option, however, we made it a *net.Dialer,
which is very restrictive (since *net.Dialer is a struct, not an
interface).
One could imagine creating a Dialer that would create pipes between
the client and an embedded server. Since Dial() returns a net.Conn,
which is an interface, everything would work the same.
Resolves #329
=> [ADDED] CustomDialer interface/option setter

nats.go, test/conn_test.go
Suppose that you have a connection with two subscriptions, let's
call them "pub" and "close".
Let's say that you know that when receiving a message on "close",
no new message will arrive on "pub" (because the sender does
send "pub" and then a final message on "close"). But because
"pub" and "close" are two different subscriptions, there is no
guarantee that the message on "close" is not going to be dispatched
before the last message on "pub".
The Barrier() API can be used to solve this issue. In the example
above, if the message callback on "close" were to call that API,
this will ensure that all pending messages on "pub" have been
dipatched before the provided function in the Barrier() API gets
executed.
See `test/TestBarrier()` test for more details.
=> [ADDED] Conn.Barrier() API

nats.go, test/conn_test.go, test/reconnect_test.go
This creates a function one can use to set the ReconnectBufSize option,
it's similar in design to the other functions already here
Also makes small fixes to some doc strings that I noticed
=> [ADDED] ReconnectBufSize() Option function

nats.go
This commit replaces the regex used to check for the string literal
'connection refused' with strings.Contains in `Conn.connect`. Using
regexp.Match requires compiling the regex on each call - since the
string being matched is a literal strings.Contains is a simpler and
more performant option here.
=> nats: simplify error check in Conn.connect

.travis.yml, nats.go, nats_test.go, test/cluster_test.go, test/helper_test.go
The server pool was only growing when new servers were discovered.
Now, the client library updates its server pool based on server's
INFO protocols (true for server 1.0.6+).
The DiscoveredServersCB is still invoked only when new servers
are added (as in never seen as opposed to added back after leaving
the cluster).
The code should work ok with older servers but will take advantage
of changes in the server (https://github.com/nats-io/gnatsd/pull/626)
=> [IMPROVED] Server pool is updated based on server notifications

nats.go
This significantly reduces memory usage when the nats Conn enters an error loop.
In a Cloud Foundry test ([route-emitter/cmd/route-emitter](https://github.com/cloudfoundry/route-emitter/blob/master/cmd/route-emitter/main_test.go)) the `Conn.processOpError` was responsible for ~95% of memory allocations.  This was due to `Conn.processOpError` allocating a new `bufio.Writer` each time it was called.  This commit changes `Conn.processOpError` to reuse and reset its existing `bufio.Writer`.
Below is the output from `go tool pprof` implicating `Conn.processOpError`:
```
File: route-emitter.test
Type: inuse_space
Time: Feb 17, 2018 at 5:54pm (EST)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top5 -cum
Showing nodes accounting for 560MB, 94.65% of 591.68MB total …
```
=> [IMPROVED] Reuse buffers in Conn.processOpError

nats.go, test/conn_test.go
I originally started `f` as a go routine, but decided not to, however doing so I should have released the locks. This is done now.
Related to #338 
Resolves #345
=> Fixed locking in Barrier when there is no async subscription

nats.go, test/conn_test.go
This manifested with the recent changes where server may send
an async INFO protocol right after sending the initial PONG to
the client.
After the client sends the CONNECT protocol, it expects to receive
a PONG. The reading of the protocol is done in place (in the
sendConnect() function) but a buffer reader was used. This is wrong
since any data/protocol sent right after by the server may be
consumed when trying to read the PONG instead of leaving that to
the readLoop.
Since we are just looking for the PONG (or OK and PONG) here, perform
a byte-by-byte read there. Alternatively, if doing a buffered read,
the buffer will have to be passed to the readLoop so that whatever
is in the buffer is read prior to resuming reading from socket.
=> [FIXED] Protocols received right after first PONG may be processed

nats.go, test/conn_test.go
Continuation of #344. We don't want to remove discovered servers
from the pool if we get an INFO with empty array. The new servers
will send arrays with at least their own URL, but older servers
or in some situations, the array could be empty (omitted) and we
should not treat this as if there were no server at all in the
cluster.
=> Skip processing of INFO.ConnectURLs when the array is empty.

README.md
Adds FOSSA scan status to README for CNCF license scans.
Ref: @caniszczyk
=> doc(readme): add license scan status

nats.go, test/basic_test.go
Related to https://github.com/nats-io/go-nats/issues/359 issue.
The new `PingInterval` function make it simpler to configure NATS connection. It's created similar way to `ReconnectWait` function. https://github.com/nats-io/go-nats/blob/master/nats.go#L534
=> Create PingInterval helper function

enc.go, nats.go, nats_test.go, netchan.go, test/conn_test.go
This is a follow up on #365. Working on another issue and running
tests, I still had a race on the original ach or a panic on send
to close channel.
Move from a channel to a linked list with dedicated lock.
=> [FIXED] Dispatching of asynchronous callbacks

nats.go, nats_test.go
When a connection is closed very quickly after being created, there
was a race condition that could lead to the connection object still
being referenced (and therefore holding resources) until the first
ping interval elapsed.
This was because the pinger was created in spinGoRoutines() which
was itself created as a go routine. When the Close() call was made,
the ping timer may still be nil (therefore no way to stop it), but
then created in the go routine (which caused the reference to the
connection object). By default, it means that the connection object
would be held for 30 seconds.
Doing connect/close in a tight loop would show the process size
growing.
This PR refactors where we create the pinger and the use of the
wait group. There had been a change in a past to attempt to fix
a …
=> [FIXED] Close() may not release resources immediately

test/conn_test.go
Some tests did still reference ssl_required (which has been
removed, tls_required is the proper field name). This has no
impact since in these tests, the value was set to false.
=> Removed use of ssl_required in test

.travis.yml, nats.go, nats_test.go, test/auth_test.go, test/conn_test.go
Added support to pass in a NoEcho option. Old servers that do not support will error.
=> NoEcho Option Support

README.md, nats.go, nats_test.go, test/cluster_test.go, test/context_test.go, test/drain_test.go, test/sub_test.go
This PR allows clients to drain subscriptions or complete connections. This allows for graceful shutdown of clients, especially queue subscribers.
on a connection drain, any errors will fire the asyncErrCB. When all publish messages have been flushed and all subscriptions drained properly the connection will move to a closed state.
=> Support for Drain Mode

nats.go, test/conn_test.go
Users may want to setup a pattern using options that could be nil. 
An example would be:
```go
var ca, cert nats.Option
if (cafile != "") {
ca = nats.RootCAs(cafile)
}
if (certfile != "") {
cert = nats.ClientCert(certfile, keyfile)
}
nc, err := nats.Connect("nats://myhost:4222", ca, cert)
```
Today this would result in a fault if an option isn't set, e.g. if a CA wasn't used.  This PR allows this pattern.
=> Allow nil options in the nats.Connect API

context.go, test/context_test.go
Currently behavior of context in the client is not deterministic when the context has already been canceled and is possible for a client to still receive messages from a request, as shown in the test occasionally failing in Travis:
```
--- FAIL: TestOldContextRequestWithTimeout (0.13s)
context_test.go:91: Expected request with context to fail
```
In order to fix this, now we check first whether the context has been canceled already previous to waiting for the message to prevent successfully making requests using an invalid context.
=> [FIXED] Request or NextMsg with Context may return message after being canceled

.travis.yml, nats.go, test/drain_test.go
=> [FIXED] Set connection's last error if async error occurs during Drain

nats.go, nats_test.go
=> Nkey support

README.md, examples/nats-bench.go, examples/nats-echo.go, examples/nats-pub.go, examples/nats-qsub.go, examples/nats-req.go, examples/nats-rply.go, nats.go, nats_test.go
Added a helper function that loads nkey seed from a file and wipes memory after each invocation.
Plugged it into the examples, and added an echo example.
=> Added nkey seed file helper and updated examples

nats.go, test/auth_test.go
This pull request adds `TokenFunc` to the `Options` struct. This adds a way to generate a new token every time a `connectProto` is built and allows the use of expiring tokens like JWTs when authenticating.
=> Add TokenHandler option to connection options

nats.go, nats_test.go
This adds support for a user JWT. This adds to bare nkey support.
We support this as a callback to support JWT upgrades while an application is running.
We support decorated formats as provided by nsc, and we support chained files that have the user JWT and the user seed in the same file.
=> Support for User JWTs

nats.go, test/conn_test.go
Allows us to auto-expand hosts that resolve to multiple IPs.
=> Auto expand with multiple hosts

nats.go
This won't pass tests until server updated, which is queue up.
=> Change to RawURLEncoding

nats.go, nats_test.go, test/auth_test.go, test/cluster_test.go, test/conn_test.go
A permission error on a subject that would have upper case would
be converted to all lower case, which is not correct.
=> [FIXED] Maintain string case in errors

nats.go
Was looking into why our nats cluster was logging occasional client side tls handshake errors, and noticed tls handshake errors in this client were being ignored.
=> Check tls handshake errors

nats.go, test/conn_test.go
If given URL is `nats://...` and the client connects to a server
that requires TLS, the library would automatically switch but
skip hostname verification.
This PR changes this behavior and by default will verify server
hostname. User will have to provide their own TLSConfig if
skipping is desired.
=> [CHANGED] Don't skip TLS hostname verification

README.md
In the following code:
```
nats.ReconnectHandler(func(_ *nats.Conn) {
fmt.Printf("Got reconnected to %v!\n", nc.ConnectedUrl())
}),
```
We're trying to access `nc.ConnectedUrl()` but we're taking the argument of `*nats.Conn` as `_` instead of `nc`
=> Fix error in reconnect handler docs.

.travis.yml, enc.go, test/basic_test.go, test/netchan_test.go, test/sub_test.go
Megacheck has been deprecated.
Dropping Go 1.9 from build matrix since staticcheck does not work
with that and Go 1.9 is technically no longer supported.
=> Replace megacheck with staticcheck

nats.go, nats_test.go
This returns the RemoteAddr().String() of the server the connection
is currently connected to.
That is, say server is running on loopback port 4222, this call
would return: "127.0.0.1:4222"
=> [ADDED] Conn.ConnectedAddr()

nats.go
=> Smarter kickFlusher on subs

.travis.yml
Similar to https://github.com/nats-io/gnatsd/pull/906 , nice to have to be able to run the build on Travis on a forked repo
=> Add go import path to Travis

context.go, nats.go, nats_test.go
If we have a msg available return immediately without setting up timeouts etc.
On my machine took NextMsg(0) from >450ns to 55ns per call.
=> Improve NextMsg() performance when msg available

nats.go
#436  Change flushChanSize from 1024 to 1.
And `fch` is already non block style.
https://github.com/nats-io/go-nats/blob/master/nats.go#L2394
https://github.com/nats-io/go-nats/blob/master/nats.go#L1272
=> Change flushChanSize from 1024 to 1.

nats.go, nats_test.go, test/conn_test.go
We were getting reports of cryptic TLS errors on NGS when the real problem was the credentials file was not found.
=> Fix for bad TLS error on bad credentials/auth

context.go, enc.go, nats.go, nats_test.go, netchan.go, test/sub_test.go
This can occur when a sync or queue sync subscription is being created at the same time the connection is being closed.
https://github.com/google/go-cloud/issues/1556
/cc @vangent
=> Fix for race on sub sync type setting

examples/nats-bench/main.go
Recent changes removed a `Fatalf` in `usage`, which exited with an `os.Exit(1)`.  With this change when the benchmark was launched without the proper number of parameters, it would continue execution after `usage` and panic.
Add `os.Exit(1)` at the end of `usage` to restore previous exit behavior.
=> Exit after usage

.travis.yml, README.md, nats.go, nats_test.go, test/auth_test.go, test/cluster_test.go, test/conn_test.go, test/helper_test.go, test/reconnect_test.go
Replaced to loopback ipv4 instead of localhost. In some cases,
when running the server with 127.0.0.1, if the application uses
the previous default URL (localhost), the library would resolve
this and possibly get 2 IPs (common to get 127.0.0.1 and ::1),
and it would then pick randomly one of those 2. If getting ::1,
and the server is listening on 127.0.0.1, the connection would
fail before it tries with the ipv4 address.
Also replaced reference of gnatsd with nats-server.
=> [CHANGED] DefaultURL changed to "nats://127.0.0.1:4222"

nats.go, test/cluster_test.go, test/reconnect_test.go
As @kozlovic proposed this PR renames handler type to be more abstract so could be reused in future.
=> renamed DisconnectErrHandler to ConnErrHandler

README.md
Adding the trailing "/" avoids an error report about "no such
file or directory"
=> Update the "go get" instructions to avoid error report [ci skip]

examples/nats-bench/main.go, examples/nats-echo/main.go, examples/nats-pub/main.go, examples/nats-qsub/main.go, examples/nats-req/main.go, examples/nats-rply/main.go, examples/nats-sub/main.go
Apply similar fix as https://github.com/nats-io/nats.go/pull/456 and call exit 1 after showing the tool usage/help message.
=> Fixes to example tools

README.md, nats.go, test/basic_test.go
This will allow a user to respond to a subscription callback that has not closed over a connection by referencing the request message.
```go
func cb(m *nats.Msg) {
m.Respond([]byte("I am here")
}
```
=> Add Respond()

nats.go, nats_test.go, test/auth_test.go, test/cluster_test.go, test/conn_test.go, test/helper_test.go, test/reconnect_test.go
Otherwise, projects pulling nats.go end-up with issues.
Resovles #478
=> Fixed nats-server import paths

README.md
`go get` needs special handling with trailing slashes when using Go modules so adding to the readme (more info at https://github.com/nats-io/nats.go/issues/478)
=> Add note to README on using go get and Go modules

nats.go, test/sub_test.go
=> Allow sync subs to allow m.Respond with auto-unsub

context.go, nats.go, test/context_test.go, test/sub_test.go
If the application is in NextMsg() (or NextMsgWithContext()) and
the subscription is unsubscribed from a different go routine, the
NextMsg() call would return that the connection is closed, instead
of the subscription.
Resolves #404
=> [FIXED] Wrong error returned in NextMsg and NextMsgWithContext

go.mod, go.sum, nats.go, nats_test.go
In general we want to retry a connection that got an auth error whether its a violation or expiration. However we want to close the connection if we get the same error twice on same server.
Also replaced code now present in jwt lib.
=> Handle expiration and auth errors on reconnects.

nats.go, nats_test.go
=> Clear lastErr on reconnect success

nats.go, nats_test.go
Move the detection/handling down to sendConnect when we know we
got an -ERR from the server. With the use of a boolean we know
if we should abort the reconnect attempts in the doReconnect loop.
=> Rework auth errors handling during reconnect

README.md
This PR proposes 2 small fixes on the README examples.
The current examples focuses on the concept introduction rather than compilable snippets.
To keep the current philosophy of the examples without having as a newcomer to dig into the `examples/` directory straight away, these fixes help to reduce the overhead of copy/pasting/editing prior the first execution.
=> README: Fix syntax errors.

README.md
Currently, there are some code examples that omit the package name. This requires the user to do a little more work on their end. They would have to know that they need the package name.
This change adds the package name to the code so it's easier to copy-paste examples.
=> Make code examples more copy-paste friendly

nats.go, nats_test.go
Currently, if you pass a path with a tilde to nats.UserCredentials it fails
because it doesn't expand the tilde to mean the user's home directory.
This change adds support to expand paths with a tilde, such as "~/.nkeys".
Resolves https://github.com/nats-io/nats.go/issues/509
=> Expand paths with tilde

.travis.yml, nats.go, nats_test.go, scripts/cov.sh
=> [FIXED] Data race between processMsg() and Stats()

nats.go, test/reconnect_test.go
Added connection option `NoCallbacksAfterClientClose` which disables the invocation of callbacks if the client code directly calls `Close()`. In case of a library initiated close, callbacks will be
invoked as they currently are.
=> [ADDED] Allow client to choose whether to execute callbacks on Close()

README.md, nats.go, nats_test.go
PR #523 introduced and issue that could cause a Request() call
to receive a reply that was intended for another Request() call
if the responder sent multiple replies for the same request.
This issue is only in v1.9.0
=> [FIXED] Request() may receive invalid reply if responder sends multiple replies

nats.go, nats_test.go
panic: runtime error: index out of range [7] with length 7
goroutine 73 [running]:
github.com/nats-io/nats%2ego.(*Conn).connect(0xc000516000, 0x0, 0x0)
/home/andrezen/go/src/github.com/nats-io/nats.go/nats.go:1466 +0x3f8
github.com/nats-io/nats%2ego.Options.Connect(0x0, 0x0, 0xc000101d40, 0x4, 0x4, 0x0, 0xc00056a160, 0x1b, 0x0, 0x0, ...)
/home/andrezen/go/src/github.com/nats-io/nats.go/nats.go:1020 +0x39a
github.com/nats-io/nats%2ego.Connect(0xc000250120, 0x8b, 0xc0005b1de8, 0xa, 0xa, 0x0, 0x0, 0x0)
/home/andrezen/go/src/github.com/nats-io/nats.go/nats.go:556 +0x2b7
gitlab.biocad.ru/ais/a2/lib/rpc_nsr_srv.(*ClientNSR).runNatsConnNc(0xc0005a8300, 0xc0000c0200, 0x0)
/home/andrezen/go/src/gitlab.biocad.ru/ais/a2/lib/rpc_nsr_srv/c.runNatsConnNc.go:14 +0x627 …
=> [FIXED] Possible panic on connect if discovered server list shrinks in that process

nats.go, test/basic_test.go, test/context_test.go
Applies only when UseOldRequest() options is passed to Connect():
If a Request() was issued and the connection closed, the Request()
call would not return with "connection closed" error, instead it
would wait for the provided timeout.
The issue would not exist in the RequestWithContext() API, even
when using the old style request, but a test has been added
nevertheless.
=> [FIXED] Request() with UseOldRequest not kicked out on Close()

.github/ISSUE_TEMPLATE/blank_issue.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/defect.md, .github/ISSUE_TEMPLATE/feature_request.md
I've adapted this PR from https://github.com/nats-io/nats-server/pull/1364.
This allows users to select a specific type of issue that they want to report, rather than using the same template to choose either a defect or feature request. A similar change was just merged into the Rust client. When you click "Open Issue", users are presented with [this menu](https://github.com/nats-io/nats.rs/issues/new/choose) before taking them to a specialized issue template. This reduces friction for reporters as they can spend less work reading and cutting irrelevant parts of the template.
This also automatically assigns the bug and enhancement labels to relevant issues opened through this form, and it also provides an "escape hatch" for users to skip the template with a blank issue if they feel the …
=> Use GitHub issue templates

nats.go, nats_test.go
After adding discovered URLs from the INFO, reshuffle the pool
if option allows
Resolves #565
=> [FIXED] Randomize discovered server URLs if allowed

nats.go, nats_test.go, test/auth_test.go, test/basic_test.go, test/cluster_test.go, test/conn_test.go, test/reconnect_test.go, test/sub_test.go
When library would wait for the reconnect wait interval, it will
now wait for a random time bounded by this value.
This prevents thundering herd reconnect issue, especially with
TLS.
Resolves #563
=> [FIXED] Added jitter in the reconnect logic

README.md, nats.go
=> Release v1.10.0

context.go, nats.go, test/context_test.go, test/headers_test.go
=> add Msg variants of the Request() functions for headers

README.md
Use pkg.go.dev site instead for the updated godoc
https://godoc.org/github.com/nats-io/nats.go ->
https://pkg.go.dev/github.com/nats-io/nats.go
=> Update GoDoc link in README

README.md, nats.go, norace_test.go, test/conn_test.go
Normally, nats.Connect() would fail if there is no server available
when this call is executed. With this new option, if no connection
can be made, this call will return no error and will trigger code
similar to the reconnect code. Therefore, MaxReconnect and ReconnectWait
options are used as if the library had been disconnected and is trying
to reconnect.
Note that subscription and publish calls will also behave as if the
library was in reconnection mode, which means that the calls are
buffered and produce no error until the reconnect buffer size is
full.
Obviously, since the connection is not connected, Flush or Request/Reply
calls would timeout.
If the ReconnectHandler is set, it will be invoked if the library
connects asynchronously.
Unrelated: fixed a test that had a t.skip()... …
=> [ADDED] RetryOnFailedConnect option

nats.go
functions like Publish will return an error when headers
are not supported, users who wish to support old and new
servers will need a way to find out if they can use headers
without parsing errors each time
=> add a helper to determine if headers is supported

nats.go, test/conn_test.go
If the library was able to create a TCP connection to a server but
failed for any reason (TLS timeout, etc..) RetryOnFailedConnect
would fail.
=> [FIXED] RetryOnFailedConnect failing if getting protocol error

nats.go, nats_test.go
Not sure if this is the right approach. The server will use inline status and descriptions for efficiency and originally we promote these to Status. Added in support for Description. Note the Go does not do this per se on HTTP.
https://golang.org/pkg/net/http/#Response
=> Add support for status line plus description

.travis.yml
Since we don't vendor in this repo, we need to use go.mod, so removing GO111MODULE=off and the go get for the nats-server (which would pull tip)
=> Fixed NATS Server dep

README.md, enc_test.go, nats.go, nats_test.go, norace_test.go, test/auth_test.go, test/basic_test.go, test/drain_test.go, test/sub_test.go
Slow consumer state still seems off, this is a first step trying to improve.
Increased the default number of pending messages limit but kept bytes the same.
Also introduced a default ErrHandler that will print out to stderr in case none has been set.
Someone needs to look deeper into why we are so imbalanced when receiving messages like queued up JetStream messages for a consumer.
=> Changes to default pending and default error handler.

context.go, enc.go, js.go, nats.go, netchan.go
Ivan pointed out that setting the jsSub portion of the low level sub after we called subscribe could cause some issues.
=> Assign jsSub during low level subscription

js.go, test/js_test.go
Fixes a few golint errors related to names:
```
js.go:54:6: type ApiError should be APIError
js.go:60:6: type ApiResponse should be APIResponse
js.go:99:2: const JSDefaultApiPrefix should be JSDefaultAPIPrefix
js.go:154:6: func ApiPrefix should be APIPrefix
js.go:164:6: func ApiRequestWait should be APIRequestWait
js.go:414:6: type ApiPaged should be APIPaged
```
=> js: Fix a few golint errors

js.go, test/js_test.go
This separates the JetStream interface into two smaller interfaces:
A `JetStream` interface used for producing and consuming messages, and a `JetStreamManager` interface for creating streams/consumers. This also adds a new interface that is the compound of both called JetStreamContext and is the one that is being returned when calling `nc.JetStream()`.
This change allows to opt-in to the behaviors provided by the `JetStreamContext` as needed, for example:
```go
// Can be used to both create streams and publish
js, err := nc.JetStream()
// Can be used to produce/consume messages, but not for creating streams
var js nats.JetStream
js, err = nc.JetStream()
// Can be used for managing streams/consumers
var jsm nats.JetStreamManager
js, err = nc.JetStream()
```
Signed-off-by: Waldemar Quevedo …
=> Separate JetStream into smaller interfaces

js.go, test/js_test.go
Adds the following options to configure the DeliverPolicy from a consumer.
- `nats.DeliverAllAvailable()`
- `nats.DeliverLastReceived()`
- `nats.DeliverNew()`
- `nats.DeliverByStartTime(time.Time)`
- `nats.DeliverByStartSequence(uint64)`
=> js: Add option to configure deliver policy from consumer

js.go, nats.go, test/js_test.go
In case a Durable name includes a dot, then it would not be able to be created since it will not match against the `$JS.API.CONSUMER.CREATE.*` subject from the JetStream API and return a `jetstream not enabled` error.
With this change, we try to detect this in the client first and error in case an invalid durable name has been used.
=> Add some validation for durable names

context.go, js.go, jsm.go
This splits `js.go` into two files to keep the management parts separated, and also changes many of the helper types to being private since many not useful outside of this package.
Also includes some Go doc fixes.
=> Make most of JS API types private, separate js and management parts

js.go, nats.go, test/js_test.go
Add suppression so that a msg is only attempted to be acked a single time (other than InProgress acks).
Fixes #634 
=> js: Prevent sending duplicated Acks

js.go, jsm.go
Once this lands will update server tests to use this vs full blown JS cluster setup here.
=> Add in support for optional cluster info for streams and consumers.

nats.go
=> js: Remove JS timeout which got moved to JS context

js.go, jsm.go, test/js_test.go
This makes the client do an extra lookup for consumer info to check whether it should attach or create automatically to avoid using `Attach`.
=> js: Make consumer attach based on durable name, remove Attach

js.go, test/js_test.go
Now that Ack can be used by non JetStream subscriptions, to subscriber directly it is only needed to use a regular subscription.
=> js: Remove PushDirect option

test/js_test.go
Adds some tests for push/pull subscribers and queue subscribers when using JS clustering mode.
=> js: Add helpers and client reconnect tests for JS cluster mode

js.go, nats.go, test/js_test.go
The result of a `Poll()` publish request could be a 503 message from the API which when processed by the SubscribeSync iterator will result in an empty message.  This adds similar handling as in `Request` to make these special messages errors instead of being passed to the user.
=> js: Handle 503 status when JS API unavailable in pull mode

js.go, test/js_test.go
Adds `QueueSubscribeSync` which can be used to create pull based queue groups.
=> js: Add QueueSubscribeSync to JS context

jsm.go, test/js_test.go
Added extra fields to StreamConfig to use mirrors.
=> jsm: Add fields for mirrors to StreamConfig

js.go, test/js_test.go
This adds the following new options to Subscribe:
```go
js.SubscribeSync("foo",
nats.Durable("test"),
nats.AckWait(5*time.Millisecond),
nats.MaxDeliver(5),
nats.MaxAckPending(3),
)
```
This also updates so that `nats.AckWait` can be used to set the timeout to wait for the ack of a Publish or AckSync:
```go
js.Publish("baz", msg, nats.AckWait(5*time.Second))
msg.AckSync(nats.AckWait(2 * time.Second))
```
=> js: Add more SubOpts: AckWait, MaxDeliver, MacAckPending

js.go, jsm.go, test/js_test.go
This adds `ConsumerNames` and `StreamNames` to `JetStreamManager`.
```go
StreamNames(ctx context.Context) <-chan string
ConsumerNames(ctx context.Context, stream string) <-chan string
```
=> jsm: Add StreamNames and ConsumerNames

js.go, jsm.go, test/js_test.go
This adds the following two APIs to JSM which can be used instead of the listers.
```go
type JetStreamManager interface {
// StreamsInfo can be used to retrieve a list of StreamInfo objects.
StreamsInfo(opts ...JSOpt) <-chan *StreamInfo
// ConsumersInfo is used to retrieve a list of ConsumerInfo objects.
ConsumersInfo(stream string, opts ...JSOpt) <-chan *ConsumerInfo
}
```
=> js: Replace JetStreamManager listers with iterators

js.go, jsm.go, test/js_test.go
This changes the management APIs to receive options.
```diff
-	AddStream(cfg *StreamConfig) (*StreamInfo, error)
+	AddStream(cfg *StreamConfig, opts ...JSOpt) (*StreamInfo, error)
```
This also updates calls that accepted a timeout to accept a context instead. The context is created from the old timeout value.
```diff
-	r, err := js.nc.Request(usSubj, req, js.opts.wait)
+	r, err := js.nc.RequestWithContext(o.ctx, usSubj, req)
```
=> Add optional JSOpts to management API

js.go
In case of using multiple PullSubscribers concurrently under the same connection, some of the pull messages could have been missed when calling `sub.Fetch(1)`.  The reason was due to the special case added for when batch == 1 to use the global request handler, but due to the [subject rewriting of JetStream](https://github.com/nats-io/nats.go/blob/master/nats.go#L3032-L3034) messages happening then this meant that some of the replies were not being returned.  As a workaround, we just switch to an old style request for the case of batch == 1 as well.
=> js: Use old request style for sub.Fetch(1)

go.mod, go.sum, test/js_test.go
Fixes`TestJetStream_ClusterReconnect/qsub_durable` which was flapping due to a couple of server restarts, also makes these tests wait for the server shutdown properly.
=> js: Fix cluster reconnect test

js.go, nats.go, test/js_test.go
Removes the `nats.DirectOnly` option which was used to lock down the client not making API lookups.
=> js: Remove DirectOnly JS Option

js.go, test/js_test.go
nats.Durable is a SubOpt that may be passed to PullSubscribe or other
methods. If a durable name isn't passed to PullSubscribe, then we return
a runtime error.
Instead of returning a runtime error for this case, this change updates
the PullSubscribe method to require a durable name parameter.
=> Make Durable mandatory for PullSubscribe

go.mod, go.sum, js.go, test/js_test.go
ChanSubscribe was incorrectly becoming a SubscriptionSync type, so there were some unexpected pending limits related slow consumer issues.
=> js: Fix ChanSubscribe acting as SubscribeSync

js.go, test/js_test.go
`msg.AckSync()` was reusing some of the `PubOpts` to be able to customize the timeout, instead we replace it and add a new AckOpt type which can be the parameter for all types of acks. This also means that it is possible now to optionally await for the response of other types of Ack, and leaves the door option to potentially add more options to the acks:
```go
wait := nats.AckWait(2*time.Second)
msg.Ack(wait) // same as AckSync(wait), but AckSync() without option is always synchronous.
msg.Term(wait)
msg.InProgress(wait)
msg.Nak(wait)
```
```go
ctx, _ := context.WithTimeout(2*time.Second)
wait := nats.Context(ctx)
msg.Ack(wait)
msg.Term(wait)
msg.InProgress(wait)
msg.Nak(wait)
```
=> js: Add AckOpts for msg.Ack()

nats.go, nats_test.go
Applies similar handling `-ERR 'Account Authentication Expired` error as with others auth expired errors.
=> Update handling of account authentication expired error

go.mod, go.sum, js.go, nats.go, test/js_test.go
This adds the following options to push based consumers:
```go
sub, err := js.Subscribe("foo", func(msg *nats.Msg) {}, nats.EnableFlowControl(), nats.IdleHeartbeat(2*time.Second))
sub, err := js.SubscribeSync("foo", nats.EnableFlowControl(), nats.IdleHeartbeat(2*time.Second))
mch := make(chan *Msg, 512)
sub, err := js.ChanSubscribe("foo", mch, nats.EnableFlowControl(), nats.IdleHeartbeat(2*time.Second))
```
When they are enabled, the client will automatically handle/skip the control messages sent by the server.  In case of push based consumers with Heartbeats, an asynchronous typed error will be dispatched so that the subscription could deleted and restarted from the given sequence:
```go
errHandler := nats.ErrorHandler(func(c *nats.Conn, sub *nats.Subscription, err error) {
if info, ok …
```
=> js: FlowControl + Heartbeats for Push Consumers

js.go, norace_test.go, test/js_test.go
This renames the `msg.MetaData` into `msg.Metadata` since a closed form compound word ([more commonly used as well](https://github.com/search?l=Golang&o=desc&q=%22Metadata%22&s=&type=Code)) plus other changes to the metadata fields from a message:
- `meta.Delivered` to `meta.NumDelivered` similar to `NumRedelivered` field in `sub.ConsumerInfo`: https://github.com/nats-io/nats.go/blob/1b16e34671b1b5add561c0b6ede3453009c837d0/js.go#L781
- `meta.Pending` to `meta.NumPending` as in `sub.ConsumerInfo`: https://github.com/nats-io/nats.go/blob/1b16e34671b1b5add561c0b6ede3453009c837d0/js.go#L783
- `meta.Stream` and `meta.Consumer` to `meta.StreamSeq` and `meta.ConsumerSeq` respectively
- `meta.StreamName` changes to `meta.Stream`
=> js: Renaming of msg metadata fields

example_test.go, js.go, nats.go, norace_test.go
This adds godoc code examples.
You can preview the documentation locally with `godoc` by running this:
```
godoc -http=:6060
```
Then open this link: http://localhost:6060/pkg/github.com/nats-io/nats.go
=> js: Add godoc code examples for JetStream

README.md
Add JetStream basic usage to readme
=> Add JetStream basic usage to readme

nats.go, test/headers_test.go, test/js_test.go
There is an [issue](https://github.com/golang/go/issues/37834) with Go and the HTTP libraries in that responses handled by its HTTP clients become represented in 'canonical form' (`X-Foo-Bar`) sometimes unexpectedly causing integration issues with proxies, APIs, legacy apps and likely compatibility with http/2 headers to some degree which require headers in lowercase, (unlike http v1 ones that are case insensitive). As a workaround, the Go docs suggest to access the [Header map directly](https://golang.org/pkg/net/http/#Header.Set) to use the fields not in canonical form.
In this PR, it is avoided during the decoding of the headers calling `CanonicalMIMEHeaderKey` in order to be able to preserve the raw version of the headers when traversing over multiple hops without causing unexpected …
=> Make Msg.Header fields case-preserving when accessed directly

js.go, test/js_test.go
When multiple concurrent subscribers start without an existing consumer, one of them would create the consumer, some of them would attach and others fail with a `consumer already exists` error.  In this change, we make the subscriptions that would have failed with `consumer already exists` error to do an extra lookup of the latest consumer info to attach instead.
=> js: Fix issue with concurrent queue subscribers creating consumer

jsm.go, test/js_test.go
=> jsm: Check that stream name is valid on AddStream // StreamInfo

nats.go, nats_test.go, test/basic_test.go, test/js_test.go, test/reconnect_test.go, ws.go, ws_test.go
Websocket protocol will be used as long as the URL scheme is `ws` or `wss`.
Note that no mixing of websocket and non-websocket URLs can be used (in the list of servers). Once a client connects, the gossip will be augmenting the URLs of that "type".
A `Compression()` option was added, which is currently documented as being used only for Websocket connections.
=> [ADDED] Support for Websocket protocol

js.go, test/js_test.go, ws_test.go
Also added missing subscription's lock when setting some fields
at the end of initialization.
Fixed some flappers and missing defers.
=> Fixed SubscribeSync that could possibly share channel across 2 subs

nats.go
There was a possible data race between AutoUnsubscribe() and the go routine dispatching messages.
=> [FIXED] Possible data race on auto-unsubscribe

examples/nats-pub/main.go, examples/nats-sub/main.go
Added 3 new optional flags to the pub & sub examples. In order to easily test a client connection with a tls enabled nats-server:
- tlscert <file>
- tlskey <file>
- tlsrootca <file>
=> [ADDED] tls in example clients

go_test.mod, go_test.sum, js.go, nats.go, test/js_test.go
- Move responding to flow control messages to be done after latest Ack
- Set larger pending limits for async subscribers with flow control
=> js: Improvements for push consumers with flow control

examples/nats-bench/main.go, examples/nats-echo/main.go, examples/nats-pub/main.go, examples/nats-qsub/main.go, examples/nats-req/main.go, examples/nats-rply/main.go, examples/nats-sub/main.go
Was trying to clean-up #597 by resolving conflicts directly from GH but that did not work well.
Decided to copy the branch from that PR, do a rebase and resolve conflict and submit new PR.
Credit of changes goes to @aricart for the original PR #597.
=> [ADDED] `--nkey` flag to enable nkey authentication using go examples

README.md
Simple change here in README.md. The version was already set to 1.11.0
in nats.go.
=> Release v1.11.0

js.go, jsm.go, nats.go, test/js_test.go
The new function is JSAccountInfo
Signed-off-by: Matthias Hanel <mh@synadia.com>
This separates concerns into give me a jetstream object and check jetstream.
Moving that logic to the nats connection to avoid dependencies with the JetStream call.
In our meeting the group generally favored opt in over opt out. 
I'm clearly expecting ppl to either copy a sample anyway and there we add the call of course.
Or if they run into this, to just ask & find this new call.
it's also opt in because the main thing that the lookup does is provide a different error. 
I noticed that the unit test for the js object appears to be broken right now.  (at least for me, even without my change)
Deleted the checks so I could show you this sooner.
If that approach is not desirec, I'll revert and add an option to …
=> [changed] JetStream function to not lookup account info & moved it

js.go, nats.go, test/js_test.go
This allows creating subscriptions that are bound to a consumer that matches the durable name, and does not attempt to create the consumer in case it is not present.
Scenarios where this option could be used is when the consumer is bound to a JetStream instance from another account and there are limited permissions, or when a consumer is created/deleted out of band and the subscription should not attempt creation to avoid misconfigurations/configuration drift.
Fixes #735
=> js: Add nats.Bind option to disable creating consumers

js.go, test/js_test.go
Adds `ChanQueueSubscribe` to the JetStream context to consume from a stream using a channel.
```go
mch := make(chan *nats.Msg, 16536)
sub, err = js.ChanQueueSubscribe("bar", "v1", mch, nats.Durable("qsub-chan"))
if err != nil {
log.Fatal(err)
}
```
Fixes #743 
=> js: Add ChanQueueSubscribe for JS

js.go
`APIPrefix` function is not very intuitive way for setting Domain, especially for developers not knowing internals of NATS or just starting with it.
@derekcollison mentioned that there was an idea to add the `Domain` alias function, so I though I could contribute and add it myself.
=> Add utility function for setting domain

nats.go, ws.go, ws_test.go
When compression is used, the full message payload need to be
assembled (in case there are continuation frames) before being
decompressed.
=> [FIXED] Websocket decompression of continuation frames

js.go, jsm.go, nats.go, test/js_test.go
These sentinel errors will allow for better handling of managing streams and consumers.
Examples:
```go
// Creating a stream when a stream does not exist.
si, err := js.StreamInfo(cfg.streamName)
if err != nil {
if !errors.Is(err, nats.ErrNoStream) {
log.Fatalf("js.StreamInfo(): %v", err)
}
_, err = js.AddStream(&nats.StreamConfig{
Name:     "foo",
Subjects: []string{"foo.>"},
})
if err != nil {
log.Fatalf("js.AddStream(): %v", err)
}
}
// Creating a consumer when one does not exist.
ci, err := js.ConsumerInfo(cfg.streamName, cfg.consumerName)
if err != nil {
if !errors.Is(err, nats.ErrNoConsumer) {
log.Fatalf("js.ConsumerInfo(): %v", err)
}
_, err = js.AddConsumer(cfg.streamName, &nats.ConsumerConfig{
AckPolicy:     nats.AckExplicitPolicy,
DeliverPolicy: nats.DeliverNewPolicy,
Durable: …
```
=> Add two new sentinel errors. ErrNoStream and ErrNoConsumer

nats.go
The `strs` slice is not used - it seems to have stuck around from [`net/textproto.ReadMIMEHeader`](https://golang.org/pkg/net/textproto/#Reader.ReadMIMEHeader).
=> Remove unused code from readMIMEHeader

jsm.go, test/js_test.go
This adds `MaxMsgsPerSubject` to `StreamConfig` and adds a test to verify the behavior.
Closes https://github.com/nats-io/nats.go/issues/749
=> Add MaxMsgsPerSubject to StreamConfig

js.go
This updates the godoc for `ExpectLastMsgId` to mention `msgId`, instead of `seq`.
Closes #773
=> Update ExpectLastMsgId godoc

nats.go, nats_test.go
=> support custom inbox prefixes

nats.go, parser.go
This PR intends to address the github issue
> may avoid unnecessary data copy in processMsg for large message payloads #787 
I've also  tweaked the benchmark test in file *test/bench_test.go* for local testing, but not included it in the PR because I am not sure of its necessity.
```go
func BenchmarkPubSubSpeed(b *testing.B)
...
//msg := []byte("Hello World")
msg := []byte(strings.Repeat("Hello", 1000))
```
=> [CHANGED] avoid unnecessary data copy in processMsg

context.go, js.go, nats.go, test/js_test.go
Use a SyncSubscription instead. The only visible change from the
user is that calling Fetch() after Unsubscribe() returns ErrBadSubscription
instead of timeout or context deadline exceeded, which makes more
sense to me. This is the only test that I had to tweak.
=> Reworked PullSubscribe implementation

js.go, js_test.go, nats.go
This would cause issues during a reconnect
=> Fixed issue where JS would change subscription subject

js.go, jsm.go, test/js_test.go
=> [ADDED] Description in StreamConfig and ConsumerConfig

js.go, test/js_test.go
=> [ADDED] ExpectLastSequencePerSubject() publish option

js.go, test/js_test.go
=> [ADDED] Last per subject delivery policy

js.go, js_test.go, test/js_test.go
This is to align with newer version of the ADR describing the
subscription workflow:
- Removed option SubjectIsDelivery that was introduced in main branch
(but not released yet).
- Take into consideration the new ACK layout
- Make sure that OrderedConsumer rejects user configuring DeliverSubject
=> Removed new option SubjectIsDelivery and some other changes

js.go, test/js_test.go
This is done to alert the user that consumer config is not changed
as one would expect.
This change is more tricky than expected. We can't simply compare
user's consumer config with what is returned from the server.
For once, there are configurations that may not be set by the
user that were set when the consumer was created, that the lib
should not fail. Let's say the consumer is created with a description,
why fail the user if they don't pass the Description() option at all?
The Description() option was actually missing, but this is a good
example. But same could be say with for instance "optional start
sequence". This may be something that is set when the consumer
is first created (possibly outside of the app with CLI), but when
user calls js.Subscribe(), that option should not have to …
=> [IMPROVED] Subscribe returns error if consumer config does not match

nats.go, test/conn_test.go
This change updates the connection status by implementing the Stringer interface, enabling users to log out the connection status in a human readable format.
I've updated an existing tests to verify the string output. It's not exhaustive, but covers the same cases the existing test exercises. If you'd rather I add a separate test that covers each permutation then let me know and I can update the pull request.
=> [ADDED] Stringer for connection status

js.go, js_test.go, test/js_test.go
This would happen when pull requests would have filled the waiting
queue in the JetStream consumer and a 408 status was returned.
Resolves #809
=> [FIXED] Fetch() could return immediately with a timeout error

js.go
Copied the go doc from implementation to interface, and reworded
some sections.
I decided to copy versus move because some IDE (for instance VS code)
seem to show the doc (when hovering) from the implementation, not
the interface.
=> [UPDATED] JetStream go doc in the interface

ws.go, ws_test.go
=> [FIXED] Websocket: possible panic when decoding CLOSE frame

js.go, test/js_test.go
This makes it so that fetch requests that receive a 408 message signal to be canceled become unblocked in case they have received a single message at least.
=> js: unblock batch requests on 408 with at least a message

nats.go
@derekcollison Please review. The price of this comparison near 2ns per operation but in case of plain subscriptions it reduces single allocation per operation and results in speedup. Looking forward for your comments. If somehow to know beforehand that subscription using wildcard then it's possible to make it no cost. So I suggest to merge this pull request first, than make some changes to subscription struct to contain isWildcard bool field and then switch to using it. so no need to compare strings just single if isWildcard and nothings else.
=> Subject interning

js.go, test/js_test.go
The deadline of a context is now used to calculate the time used for `expires` instead of the default `ttl` of the JetStream context which was `5s` by default.  This was preventing library users from passing a context with a custom timeout.
This also disallows the usage of `context.Background` to make it explicit that `sub.Fetch` has to be used with a context that has a timeout since each fetch request has to include an expire time anyway.
In case `context.WithCancel` is used, then a child context with the same duration as the JetStream context default timeout will be created. 
It is also updated to prevent using both timeout and context options with `msg.InProgress()`, `msg.AckSync()`.
Fixes #834 #833 
=> js: Fix context usage with sub.Fetch

js.go, js_test.go, nats.go
Keep track of the "sequence" of incoming messages that are then compared with the number of delivered message.
However, ChanSubscription were broken: the FC would *always* be responded to when received, because pMsgs (and pBytes) would always be 0 for these type of subscriptions.
We now check for flow control on all incoming messages for ChanSubscription (and evaluate the "delivered" count based on the incoming sequence minus length of the user's channel). We also have a long-lived go routine to cover situations where the evaluation during the incoming message did not result in the target to send the FC, but then the user consumes enough messages to bring the "delivered" at or past the target. Without this go routine, the client would stall and have to wait for an heartbeat with the "fc …
=> [FIXED] JetStream flow control may stall in some conditions

js.go, nats.go, test/js_test.go
Relates to: https://github.com/nats-io/nats.go/issues/857
Introducing dedicated err for case when trying to ack msg that was already acknowledged.
=> More meaningful message when trying to ack message that was already acknowledged 

js.go, kv.go, nats.go, test/js_test.go, test/kv_test.go
Can now attach a context to a subscription so that it is unsubscribed and/or consumer deleted via propagation of cancellation via parent context.  This helps specially with `kv.Watch` functions that have an ordered consumer subscription.
=> js: make js.Subscribe context aware

js.go
Signed-off-by: Matthew DeVenny <matt@boxboat.com>
When `removeSub` calls `jsi.hbc.Stop()` it is possible that the timer has already expired
https://github.com/nats-io/nats.go/blob/main/nats.go#L3919
from `timer.Stop()`
```
For a timer created with AfterFunc(d, f), if t.Stop returns false, then the timer has already expired 
and the function f has been started in its own goroutine; Stop does not wait for f to complete before 
returning. If the caller needs to know whether f is completed, it must coordinate with f explicitly.
```
This PR checks to see if `sub.closed == true` and returns
=> Fix jetstream removeSub logic

nats.go, nats_test.go
If no port is specified in the URL, port 80 will be used if scheme
is "ws://" and port 443 will be used if scheme is "wss://".
Resolves #876
=> [IMPROVED] Websocket: use 80/443 as default ports

jsm.go, test/js_test.go
Updates to return `ErrStreamNotFound` when using `AddConsumer` against a missing stream.
=> Handle AddConsumer stream not found error

nats.go
Currently, the comment for `Subscribe` method contains information about the wrong separator for subjects.
=> Extended comment for Subscribe method

go_test.mod, go_test.sum, js.go, jsm.go, test/js_test.go
Namely: MaxRequestBatch, MaxRequestExpires and InactiveThreshold
=> [ADDED] JetStream: UpdateConsumer and new consumer config's options

go_test.mod, go_test.sum, js.go, test/js_test.go
=> [ADDED] JetStream: Nak delay and BackOff lists

js_test.go, nats_test.go, norace_test.go, test/cluster_test.go, test/conn_test.go, test/drain_test.go, test/js_test.go, test/kv_test.go, test/norace_test.go, test/object_test.go, test/sub_test.go
- JS Servers need a special sequence on shutdown. Most of the time
the store was attempted to be removed before the server was shutdown,
which on Windows would result in an error and the next test may
recover the previous state.
- Made use of the jsClient() helper to remove typical connect+jetstream
code.
- Added some nats.Timeout() during connect so that Windows connect
to a server that is not running is faster than the default 2sec, which
may cause tests to run very long or simply fail.
=> Fixed tests to run on Windows + some cleanup

.words, context.go, enc.go, js.go, jsm.go, nats.go, object.go, parser.go, test/conn_test.go, ws.go
The new `gospel` tool, <https://github.com/kortschak/gospel>, uses hunspell libraries but pre-registers as acceptable words every symbol from the Go source, massively reducing the noise and making comment spell-checking a tractable problem.  It recently gained support for a `.words` file located in the same directory as the `go.mod` file, to define local words.  With this, we can fix real issues too.
This PR reduces the complaints down to 4:
1. A reference to `syncSubscribers` which I can't figure out
2. A reference to a `pubArg`
3. Two references to `splitArgs`.
I made two actual code changes:
1. Fixing a **non-exported** const type for consistency with all the others: `apiStreamList` -> `apiStreamListT`.
2. Changing an error message to refer to a field which exist
Lots of typo fixes; …
=> Spelling fixes, mostly comments

go_test.mod, go_test.sum, js.go, kv.go, nats.go, test/kv_test.go
1. If the underlying stream was very busy pending might not go to zero, so snapshot and mark initial state done when received >= init pending or delta == 0
2. When a watcher was cancelled with a context we would not signal to allow and range w.Updates() calls to exit.
3. General flow control checks were timing sensitive after the initial checks, needed to be 2x HB interval always, not just beginning.
=> Updates to KV Watcher.

js.go, kv.go, nats.go
Relying on ConsumerInfo.NumPending on create does not always work
if the NATS subscription exists before (which is normal case)
due to a design in the server that process the add consumer
request and then computes the consumer info (after the consumer
is setup which means it could start to deliver messages).
Changed a bit so that we add a JS consumer without attached
subscription and use internal option to allow a js.Subscribe()
with a bind to existing consumer.
=> Updates to KV

kv.go
Signed-off-by: Matthew DeVenny <matt@boxboat.com>
Add `GetRevision` to allow retrieval of historical key value versions by revision number
=> Add GetRevision to nats.KeyValue

kv.go, test/kv_test.go
There is a breaking change where PurgeDeletes() accepts now a list
of PurgeOpt, not WatchOpt.
We needed from WatchOpt only the context, and as it standed, it was
bad since user could have passed the IncludeHistory() option to
PurgeDeletes(), which would likely "break" the functionality.
Also, when invoking PurgeDeletes(), the delete markers than are older than
a default of 30 minutes will be deleted, however more recent ones will
be kept. The data is always removed, even if a marker is not.
The user can change the 30 minutes threshold using a new purge
option called DeleteMarkersOlderThan(duration). If set to -1,
it restores the old behavior of deleting delete/purge markers,
regardless of their age.
=> [CHANGED] PurgeDeletes() will now keep markers that are less than 30min old

kv.go, test/kv_test.go
If the user creates a JS context with a custom prefix, this needs
to be used for the subject of the Put() and Delete() operations.
This is addressing the architecture design ADR-19.
=> [FIXED] KV use of JS prefix

nats.go, nats_test.go
The failure to connect would be "no nkey seed found". It will now
be more explicit:
```
error signing nonce: unable to extract key pair from file "myfile.creds": no nkey seed found
```
=> [IMPROVED] Connect error when given an invalid user creds file

js.go
When calling js.Subscribe() (or equivalent) and the library ended-up
creating the JS consumer, a MaxAckPending was set to a very high
value in some cases. We now let the server pick the default if the
value is not explicitly set by the user.
The NATS subscription pending limits are set in a way to ensure
that the subscription can store at least the max ack pending value.
=> [CHANGED] JS: Do not set MaxAckPending to high value on Subscribe

nats.go, ws.go, ws_test.go
This was due to the fact that server sends a websocket CLOSE protocol,
to which the library tried to respond to, but since it was done during
the "connect" handshake under the connection lock, this caused a
deadlock.
Resolves #925
=> [FIXED] Websocket: deadlock on authentication failure

jsm.go, kv.go, kv_test.go, nats.go, test/kv_test.go
This is related to #900 that introduced the change of discard
policy if connecting to a server v2.7.2+.
The CreateKeyValue() API calls AddStream(). If the stream already
exists and the configuration is identical, the call succeeds
(idempotent). However, since we now try to set the discard policy
to "new" when connecting to a server v2.7.2+, the call will fail
if the KV store already existed (CreateKeyValue() was called with
a v2.7.1 server and stream was created with DiscardOld).
The approach here is that if AddStream() fails with an "already in use"
error, then we will lookup the stream info, and if we detect that
the configuration is same (except for the discard policy), then
we call UpdateStream() with the new discard policy.
The problematic part is that the client side configuration …
=> KV: changing discard policy would fail on srv upgrade

jsm.go
Make same as consumer by adding prefix.
=> Add `nats: ` prefix to stream info errors to match consumer info

kv.go, object.go
=> Allow KV and Obj to specify placement options.

kv.go
Signed-off-by: Matthew DeVenny <matt@boxboat.com>
Currently if you wish to extend the `nats.KeyValue` interface, when implementing `Watch` you have no means to get at the `nats.Context` option if it has been set on the `nats.KeyWatcher`. This PR proposes a method to the nats.KeyWatcher to access that context.
=> Expose nats.Context option for nats.KeyWatcher

context.go, nats.go, test/headers_test.go
`RequestMsg` and `PublishMsg` were not checking for headers support under the lock so there was a race condition with async INFO protocols.
=> Fix race with async INFO and header APIs

nats.go, nats_test.go
The client will attempt reconnect when `maximum connections exceeded` error is sent by server immediately prior to a hard disconnect rather than close without reconnect attempt(s).
This is additive to existing re-connection on stale connection from server, auth and perm errors, and read loop errors (such as network disconnect).
=> Enhance client to do reconnect on max connections from server

js.go, js_test.go
This is an alternative implementation to enable tracing of requests in the JetStream context #849, using the same idiom of a struct with callbacks as the `httptrace` package (https://golang.google.cn/pkg/net/http/httptrace/#ClientTrace). 
```go
js, err := nc.JetStream(&ClientTrace{
RequestSent: func(subj string, payload []byte) {
log.Printf(">>> %s: %s", subj, string(payload))
},
ResponseReceived: func(subj string, payload []byte, hdr Header) {
log.Printf("<<< %s: %s", subj, string(payload))
},
})
```
=> Add ClientTrace struct for JS tracing

js.go, test/js_test.go
This makes async publishing stall wait customizable via the `StallWait` option, also sets the default stall pending default to 4K.
=> Set async pub ack inflight pending default to 4K, add StallWait option.

example_test.go, js.go
- Added BackOff helper method to set backoff through subOpts
=> Added BackOff helper method to set backoff through subOpts

examples/nats-echo/main.go
Add a service subject that isn't load balanced for example/demonstration purposes.
=> Add a standard subscription [ci-skip]

examples/nats-echo/main.go, examples/nats-pub/main.go, examples/nats-qsub/main.go, examples/nats-req/main.go, examples/nats-rply/main.go, examples/nats-sub/main.go
=> Update usage for demo servers

kv.go, test/kv_test.go
I've been testing out the experimental KV functionality, and conditional delete and purge would be very useful to us.
It appears to work out of the box on the server too in my limited testing. If you're happy with the naming and implementation I will flesh out the tests more.
=> Proposal: Conditional delete and purge for KV

object.go, test/object_test.go
Add a MaxBytes configuration option to the object store API.
=> Add a MaxBytes configuration option to the Object Store

js.go, test/js_test.go
This allows for differentiating between the zero value and whether it was intentionally
set to a sequence of zero.
Signed-off-by: Byron Ruth <b@devel.io>
=> Change expected last sequence pub options to pointers

js.go, test/js_test.go
For fetch batches of n > 1, sometimes the client would receive a 408 Requests Pending status messages for Fetch requests (initial request with no wait + expires time) which resulted in the client skipping these errors until reaching the deadline.
In this PR we add special handling for this status so that the client makes a request without no_wait after getting a 408 status with requests pending.
=> js: handle 408 fetch requests pending status

.words, .words.readme, js.go
Fix a spelling mistake which made it through to go docs.
gospel 1.13.0 is now out, and it added features which let us remove some old words (eg, pluralizations of types we define), but it also errored out on seeing a comment in .words which used to be acceptable.  So remove comments from .words and introduce .words.readme instead.
We lose the section-introducer comments.  Which is a shame.
=> spelling fix & dictionary updates

nats.go, ws.go, ws_test.go
This is a PR to fix the issue described here: https://github.com/nats-io/nats.go/issues/859
=> Add WS ProxyPath option

go_test.mod, go_test.sum, js.go, jsm.go, test/js_test.go
Namely for pull consumers: ability to override the replica count or storage type:
```go
// Generally inherited by parent stream and other markers, now can be configured directly.
Replicas int `json:"num_replicas"`
// Force memory storage.
MemoryStorage bool `json:"mem_storage,omitempty"`
```
For the stream, this new StreamConfig option:
```go
// Allow republish of the message after being sequenced and stored.
RePublish *SubjectMapping `json:"republish,omitempty"`
```
Where SubjectMapping is:
```go
// SubjectMapping allows a source subject to be mapped to a destination subject for republishing.
type SubjectMapping struct {
Source      string `json:"src,omitempty"`
Destination string `json:"dest"`
}
```
=> [ADDED] Stream RePublish and some ConsumerConfig new fields

js.go, test/js_test.go
=> Fix sending ack when AckNonePolicy is set

.gitignore, js.go, jsm.go, kv.go, nats.go, object.go, test/js_test.go
This addresses https://github.com/nats-io/nats-architecture-and-design/issues/4
=> ADDED: support for enhanced stream purge in JetStream

js.go
For ordered push semantics no need to have file based, so force R1 and memory based.
=> Ordered will force R1 and memory storage

js.go, jsm.go, test/js_test.go
This PR addresses https://github.com/nats-io/nats-architecture-and-design/issues/10
=> ADDED: option to fetch deleted details in stream info

jsm.go, test/js_test.go
=> Align RePublish with server and add HeadersOnly, also add in AllowDirect option

js.go
Based on user confusion on what the `durable` argument should be for an ephemeral consumer. The `Subscribe` method notes calls out `nats.Durable`, but not the argument itself.
=> Add additional note to JetStream.PullSubscribe on durable semantics

object.go
The old code might miss the last object if `Reader` return both a value and `EOF`
Extract from `Reader` doc :
> When Read encounters an error or end-of-file condition after successfully reading n > 0 bytes, it returns the number of bytes read. It may return the (non-nil) error from the same call or return the error (and n == 0) from a subsequent call. An instance of this general case is that a Reader returning a non-zero number of bytes at the end of the input stream may return either err == EOF or err == nil. The next Read should return 0, EOF.
>
> Callers should always process the n > 0 bytes returned before considering the error err. Doing so correctly handles I/O errors that happen after reading some bytes and also both of the allowed EOF behaviors.
=> Update object Put to avoid loosing last chunk

nats.go, test/basic_test.go, test/conn_test.go
I would like to be able to report things like ciphers,
tls or not, verified or not etc in nats account info
where its shows other connection properties but had
no way to get at this information
=> Expose TLS connection state when possible

jsm.go, test/js_test.go
[FEAT] added `SubjectFilter` to `StreamInfoRequest`. The field takes a subject/wildcard that instruct the request to provide information on matching subjects in `StreamState`.
[FEAT] added `NumSubjects` to `StreamState` enabling report for the number of subjects in the stream
[FEAT] added `Subjects` to `StreamState` a map of subject to the number of messages with the subject which gets populated if the `StreamInfoRequest` specifies a `SubjectFilter`
FIX #1009
=> Added support for Subject reporting on StreamInfo requests

nats.go
Currently finding out the defaults when using the code is a bit cumbersome: most IDEs will give you the docs for the option (e.g. `nats.MaxReconnects`), which currently doesn't mention the defaults. So you have to go to the full docs and click around before getting to the constants.
I propose adding the current defaults directly to the method/struct docs, so they are easier to find when coding, without "breaking the flow".
This has the downside of needing more care to be kept up-to-date, but I would argue the trade-off is worth it.
WDYT?
=> docs: mention defaults in option docs

nats.go
The flusher could fail the write and the user would not be able to handle nor get alerted to this error.
Although this is still poor since the error occurs asynchronously, at least the user will be alerted to the error having happened.
=> flusher errors now do not fail silently

js.go
This was a bug @piotrpio found where passed consumer name (assuming a durable) was being used to define the "next message" subject. This resets it if an ephemeral was created using the server-generated name.
=> [FIXED] Ephemeral PullConsumer's Fetch() would fail with "no responders"

nats.go, nats_test.go
This PR is an extension of the work from nats-io/nats-server#2360 by allowing a client to use an in-process connection to the NATS server, rather than a TCP connection. Much of the justification is in the other PR, but this lets us do something like:
```
natsServer, err = natsserver.NewServer(&server.Options{
ServerName: "monolith",
DontListen: true,
JetStream: true,
})
if err != nil {
panic(err)
}
go natsServer.Start()
if !natsServer.ReadyForConnections(time.Second * 10) {
panic("not ready in time")
}
nc, err := natsclient.Connect("", natsclient.InProcessServer(natsServer))
if err != nil {
panic(err)
}
```
=> In-process connections

js.go
fix nil pointer dereference when jsi is not inited
=> ConsumerInfo fix nil pointer dereference

jsm.go, test/js_test.go
Related issue: https://github.com/nats-io/nats-architecture-and-design/issues/120
=> [CHANGED] Update account info schema

go_test.mod, go_test.sum, js.go, jsm.go, test/js_test.go
This PR brings in client support for https://github.com/nats-io/nats-server/pull/3325, which adds server support for direct gets by a particular subject. This should now allow direct gets to work with KVs properly
=> Support Direct Gets by subject

kv.go, kv_test.go
Ability to create a KV with the re-publish feature.
=> [ADDED] KeyValue: RePublish option in KeyValueConfiguration

jsm.go, test/js_test.go
This addesses https://github.com/nats-io/nats-architecture-and-design/issues/118
As mentioned in the above issue, the old `DeleteMsg()` now sets `no_erase` to `true` by default (for better performance), and the new `SecureDeleteMsg()` can be used to completely overwrite the deleted message on server.
=> [ADDED] SecureDeleteMsg method to JetStreamManager

jsm.go
=> [UPDATED] Align StreamSourceInfo schema with server

jsm.go
I would like to merge that to main so I can have a server PR that pulls nats.go main and fixes the date formatting. Then I will have another nats.go PR to remove the temporary code and point to the latest from server main.
=> Temporary code change so that server PR can run tests

nats.go, nats_test.go
The motivation for this is to support situations when the JWT and seed are passed as environment variables or other means that don't rely on a file, such as environments only supporting environment variables.
=> Add UserJWTAndSeed helper function

object.go, test/object_test.go
Resolves #1042 
1. Decode digest hash without `SHA-256` prefix
2. Move verifying digest match to `Read()`, in order to return error on e.g. `ReadAll()` Additionally, this bypasses lock set by `Read()` which prevents us from setting error on `ObjectResult`.
=> [FIXED] Hash decoding in object store, propagate errors from Get() correctly

nats.go, nats_test.go
=> [FIXED] Trailing comma at end of URL lists should be ignored

js.go, jsm.go, test/js_test.go
=> [ADDED] Filter streams by subject

js.go
If you are the only client pulling on a given consumer, the efficiency gains of fetching in batches is largely lost if you have to acknowledge every message you received individually afterwards.
It would seem intuitive to be able to acknowledge only the most recent message in the batch instead and to have that do the right thing.
=> Allow `AckAll` for pull-based consumers

object.go, test/object_test.go
* Prevented links in meta data for puts
* refactored for common publish meta functionality
* Converted all loose errors to vars.
* Updated unit test to check and cover errors.
=> link not allowed in put meta

jsm.go
Might need this to allow explicit disablement for KV streams.
=> Make explicit for server processing

jsm.go, object.go, test/js_test.go, test/object_test.go
=> [ADDED] Listing buckets and bucket names

nats.go, test/auth_test.go, test/cluster_test.go
The server can send both `-ERR 'Authorization Violation'` or `-ERR 'authorization violation'` depending on some conditions so in the client side we usually try to normalize the behavior by changing to lowercase when checking for an error.
One exception was during the initial connect where the client instead returned the raw error protocol message.
Since this behavior has been in the wild for many years, instead of returning the raw error or the proper error type like `ErrAuthorization` to keep things backwards compatible just in case, this adds a new `natsProtoErr` that can be used with `errors.Is` to check whether the raw protocol message is equivalent to other errors.
Fixes #1081
=> Add natsProtoErr that can be used with errors.Is

example_test.go, js.go, js_test.go
This allows forcing memory storage through sub options while subscribing.
=> Add option to set memory storage to true for a consumer

js_test.go, jsm.go
If a subject filter is specified in the StreamInfoRequest{} option,
then all matching subjects will be returned and not be capped to
the server limit of 100,000. It is internally using pagination
that was added in the server PR: https://github.com/nats-io/nats-server/pull/3454
=> [CHANGED] StreamInfo() will now return all subjects when requested

js.go, jserrors.go, jsm.go, test/js_test.go
=> Adjust consumer creation to nats-server v2.9.0

kv.go, test/kv_test.go, test/object_test.go
=> [ADDED] Listing KeyValue store and KeyValue store names

js.go, test/js_test.go
Addresses https://github.com/nats-io/nats-architecture-and-design/issues/156
=> [CHANGED] Remove restriction on AckNone policy for pull consumers

object.go, test/object_test.go
Addresses https://github.com/nats-io/nats-architecture-and-design/issues/155
This PR introduces breaking changes to object store method signatures, as object store is still in experimental preview state.
=> [CHANGED] Hide deleted objects by default

kv.go
Currently, in order to get the size in bytes of a bucket people are resorting to getting the stream info directly adding themselves a hard coded "KV_" prefix to the bucket name which is not great and not future proof. This exposes `Bytes()` which is already present in `s.nfo` in KeyValueBucketStatus.
=> [ADDED] Exposes Bytes from stream info in KeyValueStatus

js.go, js_test.go, test/js_test.go
Addresses: https://github.com/nats-io/nats-architecture-and-design/issues/162
Resolves: https://github.com/nats-io/nats.go/issues/1094
This PR changes:
- Ordered consumer will now be recreated on missing heartbeats (failed activity check)
- Timeout or no responders on resetting ordered consumer is no longer considered terminal error - operation will be retried on subsequent failed heartbeat checks
=> [CHANGED] Ordered consumer recreate on missing heartbeat

js.go
Signed-off-by: Sylvain Rabot <sylvain@abstraction.fr>
=> Improve durable consumer unsubscribe comment

jsm.go
Looking at the schema seems it should have been `tiers`: https://github.com/nats-io/nats-architecture-and-design/issues/120
=> js: Fix typo in AccountInfo JSON to handle Tiers

kv.go, object.go, test/kv_test.go, test/object_test.go
This PR addresses https://github.com/nats-io/nats-architecture-and-design/issues/154
This PR changes the signatures of `KeyValueStores()` and `ObjectStores()` methods. For KV, this is not a breaking change since this functionality is yet to be released. For object store, **this is a breaking change** since these methods were released as part of v1.17.0.
=> [CHANGED] Listing Key Value stores and object stores to return status instead of interface

js.go
These hadn't been updated after nats-io/nats-server#3190 seemingly.
=> Update `InactiveThreshold` comments

js.go, jsm.go, kv.go, test/kv_test.go
Also updated state for proper Put() and Get() semantics with mirrors and across domains, e.g. leafnodes.
In practice when a mirror is across a domain, should be named the same as origin. That allows an app to run anywhere without anything special in terms of domains when binding to the KV itself.
=> Added support for KV mirrors and sources.

kv.go, test/kv_test.go
Updated so connecting to mirror would allow watchers to work.
=> Use BindStream for watcher so it works with mirrors.

jsm.go, kv.go, test/js_test.go
=> Support stream alternates

nats.go
=> [IMPROVED] Comment on RetryOnFailedConnect

README.md, nats.go
- JetStream:
- [BREAKING CHANGE] Extract `nats: Consumer Deleted` server error to `ErrConsumerDeleted` variable. This error is returned when consumer is deleted while waiting on pull request and was introduced in nats-server v2.9.6 (#1125)
- JetStream:
- Fix broken comments on `ErrConsumerNameAlreadyInUse` and `StreamNameBySubject()` (#1128)
- Core NATS:
- Improve comment on `RetryOnFailedConnect` connect option (#1127)
=> Release v1.20.0

nats.go, test/conn_test.go
=> [ADDED] ConnectHandler invoked on initial successful connect

kv.go, kv_test.go
=> Add ErrKeyExists on kv.Create

jserrors.go, kv.go, kv_test.go
Follow up from (https://github.com/nats-io/nats.go/pull/1135)
This changes the returned error on `kv.Create` now to be wrapping the APIError and show error information relevant to the `kv.Create` API as well:
```
nats: wrong last sequence: 1: key exists
```
instead of:
```
nats: wrong last sequence: 1
```
The wrapped error makes it possible to make checks like this as well:
```go
_, err = kv.Create("key", []byte("1"))
if !errors.Is(err, ErrKeyExists) { ... }
```
And also still possible to get the original `APIError` if needed:
```go
_, err = kv.Create("key", []byte("1"))
var aerr *APIError
if errors.As(err, &aerr) { ... }
```
=> Add ErrKeyExists that is compatible with errors.Is on kv.Create

nats.go, nats_test.go
Addresses https://github.com/nats-io/nats-architecture-and-design/issues/170
=> [ADDED] IgnoreAuthErrorAbort option on Connect

example_test.go, nats.go, services/service.go, ws_test.go
Follow up from https://github.com/nats-io/nats.go/pull/1146
This adds a small interface `SkipTLSHandshake() bool` that when implemented a `CustomDialer` may opt into skipping the handshake if not needed by the dialer implementation.
/cc @oderwat
=> Add SkipTLSHandshake optional function to CustomDialer

js.go, jserrors.go
Without this change, it makes it hard for clients to handle consumer errors relating to leadership changes differently from any other error.
Follows same approach as ErrConsumerDeleted.
=> Provide a way to handle 409 Leadership Changed errors in client

nats.go
This is required when attempting to safely modify existing callbacks from a different package.
=> [ADDED] Getters for connection callbacks

micro/example_package_test.go, micro/example_test.go, micro/request.go, micro/service.go, micro/service_test.go
- got rid of uppercasing the monitoring subjects
- removed `error` from `RequestHandler` signature
- count respond errors in stats
=> [CHANGED] Service API adjustments

README.md, nats.go
- Service API:
- Monitoring subjects for a service are no longer uppercase (#1166)
- Changed `RequestHandler` signature to no longer return an error (#1166)
=> Release v1.22.1

nats.go
Always forget whether `nats.ReconnectBufSize(0)` or `nats.ReconnectBufSize(-1)` disables it so adding to the docs.
- `nats.ReconnectBufSize(0)`: Uses default reconnect buf size
-  `nats.ReconnectBufSize(-1)`: Disables and throws outbound buffer limit error when publishing while disconnected
=> Add note on disabling reconnect buffer

micro/service.go
Since Go JSON will Marshal time.RFC3339 and back this maintains compatability while making it more convenient to use
=> use more convenient time.Time for Started

micro/example_handler_test.go, micro/example_package_test.go, micro/example_test.go, micro/request.go, micro/service.go, micro/test/service_test.go
- changed `micro.Request` to an interface
- moved tests to test package
=> [CHANGED] Use interface instead of struct for micro.Request

nats.go, test/auth_test.go
On `nats.Connect` only the last error when attempting to connect will be reported, so a failure to connect with a bad configuration will result in `no servers available` in case there are multiple servers discovered or configured. In case of using credentials, this will hide issues like not configuring correctly the path to the credentials and just getting an Authorization Error for example as well.
To improve usability we can check whether the creds have been configured correctly when processing the option rather than waiting to connect (have stumbled upon this issue a couple of times so this should improve usability).
Also started to adopt wrapping errors syntax to check for the underlying io error.
=> Check whether credentials are missing before using them

jsm.go
Optimize add consumer to not re-define the consumer if the consumer config is equal to the current consumer config
=> [OPTIMIZE] optimize add consumer

micro/example_test.go, micro/service.go, micro/test/service_test.go
- updated service schemas configuration according to ADR
- fixed empty fields in STATS response
=> [CHANGED] Service schemas

js.go, test/js_test.go
This PR uses Custom Inbox prefix in JS async reply. It should fix #1189 
Signed-off-by: Guillaume Delbergue <guillaume.delbergue@hiventive.com>
=> js: use custom inbox prefix in async reply

jserrors.go, test/js_test.go
Follow up from #1200, test condition that can bind to stream without matching subjects and consumer would start working after stream updates to include the subject that the consumer was matching originally, plus cleanup commented out test.
=> js: mirror test updates

.travis.yml, go.mod, go_test.mod, js_test.go, nats.go, rand.go
Adds Go 1.20 and also deprecates use of rand.Seed in the client for Go +1.20 series since this is now always done by default (https://github.com/golang/go/issues/54880)
=> Go 1.20 updates, add build tag for rand.Seed

nats.go
Sometimes we want NATS to avoid resolving the IP address of a host. For example, when using a proxy that only lets a specific address connect and blocks everything else.
This is why I added a new option in this PR. It lets you skip the hostname lookup.
=> Add option to skip host lookup

js_test.go
Since 2.9.15, the server handles inbound messages in a separate execution context, which is an optimisation, but it also means clients can't rely on flushing published messages to ensure that JetStream has it stored and accounted. That behaviour was never guaranteed, and it worked only because of the lack of this optimisation.
=> Fix TestJetStreamStreamInfoWithSubjectDetails test

js.go
This PR adds separate reply subjects for each pull request sent with `Fetch()` or `FetchBatch()`. This allows us to ignore timeouts from different calls.
=> [CHANGED] Use different subjects per PR when using Fetch and FetchBatch

js.go
This reverts the change from #1237 regarding logic in `Fetch()`. This requires careful consideration and while the fix for `FetchBatch()` is straightforward, in `Fetch()` the logic is a bit more convoluted, since we may be sending more than one pull request within a single `Fetch()`, with/without `no_wait` etc.
`Fetch()` will still be using wildcard subscription and distinct subjects per call, but the logic for ignoring timeouts from different invocations is reverted.
=> Revert Fetch() behavior to not verify request ID

micro/service.go
Refactored the code for setting up the monitoring verb handlers for microservices. Made the naming more intention-revealing, the code more table-driven.
NOTE: This is my first PR to this repo, I am filing it largely for learning the process.
=> style: more intention-revealing microservice monitoring setup

micro/service.go, micro/test/service_test.go
It is quite hard to validate in a way that allows object or nil using jsonschema so metadata should either be omitempty or always be object.
During initial reviews we made it not omitempty, so this ensures its never nil.  Can also make it omitempty if cleaner.
=> avoid producing nil metadata

enc.go
accessing the err property of Conn is not thread safe. This uses the getter method with proper locks.
=> Fix possible race on EncodedConnection LastError

kv.go
Fixes https://github.com/nats-io/kubecon-contribfest/issues/1
Adds KVError type to allow wrapping APIError.
E.g.:
```go
return KVError{apiError: ErrStreamNotFound, message: ErrBucketNotFound}
```
=> KVerror type wraps APIError

object.go, test/norace_test.go
- Fixed failing `TestNoRaceObjectContextOpt` test
- Fixed `Put` purging partial object before acks for all sent chunks were received. This caused leftover chunks to be processed after purge
- Fixed issue in `Read` where nil was returned instead of context error
=> [FIXED] Object store context put and get issues

example_test.go, js.go, test/js_test.go
This adds `SkipConsumerLookup()` `SubOpt,` allowing to omit calling `CONSUMER.INFO` when creating JetStream subscription.
=> [ADDED] SkipConsumerLookup option in js.Subscribe()

jetstream/test/helper_test.go, test/js_test.go
Some clustered tests were failing with "Unable to start NATS Server in Go Routine" panic from server.
This was most probably caused by client choosing random server/cluster ports, where it sometimes chose same port more than once, as observed by adding this log after each test using `withJSCluster()`
```
=== RUN   TestJetStreamConsumerReplicasOption/TestJetStreamConsumerReplicasOption-3
Server 0 , server name:  NODE_0 , server port:  38473 , cluster port:  44391 , routes:  [127.0.0.1:44391 127.0.0.1:44625 127.0.0.1:38473]
Server 1 , server name:  NODE_1 , server port:  39243 , cluster port:  44625 , routes:  [127.0.0.1:44391 127.0.0.1:44625 127.0.0.1:38473]
Server 2 , server name:  NODE_2 , server port:  45755 , cluster port:  38473 , routes:  [127.0.0.1:44391 127.0.0.1:44625 …
```
=> [FIXED] Flaky tests picking same ports more than once

js.go, object.go
Async reply subscription was created on each `object.Put()` and not cleaned up. This PR closes this subscription after `Put()` completes.
=> [FIXED] Cleanup reply sub after putting object

jetstream/README.md
The options right below the example are correct, but the example itself uses what I assume are outdated method names.
=> Fix incorrect example in jetstream README

jetstream/pull.go
Hi, I opened the issue #1279 and give a try to fix it. It seems that some code using the pending field on the pull struct was not protected at certain point. 
With the help of the stacktrace of the datarace I fixed it.
=> jetstream: fix datarace when using consumer #1279

micro/example_test.go, micro/service.go, micro/test/service_test.go
Addresses https://github.com/nats-io/nats-architecture-and-design/issues/220
=> [CHANGED] More verbose endpoint info on INFO requests

examples/jetstream/js-consume/main.go, examples/jetstream/js-fetch/main.go, examples/jetstream/js-messages/main.go, examples/jetstream/js-next/main.go, examples/jetstream/js-parallel-consume/main.go, jetstream/README.md, jetstream/consumer_config.go, jetstream/jetstream.go, jetstream/options.go, jetstream/ordered.go, jetstream/publish.go, jetstream/stream.go, jetstream/test/consumer_test.go, jetstream/test/jetstream_test.go, jetstream/test/message_test.go, jetstream/test/publish_test.go, jetstream/test/pull_test.go, jetstream/test/stream_test.go
- Fixed typo in `PullThresholdBytes` option
- Removed push consumer only fields from `ConsumerConfig`
- Removed `context.Context` from `PublishAsync` and `PublishMsgAsync`
- Renamed `AddConsumer` to `CreateOrUpdateConsumer` - this change is introduced in anticipation for separation of create and update operations in nats-server. After they'll be introduced, there will be 3 methods:
- `CreateOrUpdateConsumer()` - current upsert behavior
- `CreateConsumer()` - will not overwrite consumer
- `UpdateConsumer()` - will fail if consumer does not exist
=> [CHANGED] Simplified JetStream API changes and improvements

README.md, nats.go
This release focuses on improvements to new JetStream API and Service API (`micro`) preview functionalities.
- JetStream Simplified API:
- `StreamNameBySubject()` method for stream discovery based on provided subject (#1292)
- JetStream Simplified API:
- Simplified lock handling for `Consume()` and `Messages()` (#1303)
- JetStream Simplified API:
- [BREAKING CHANGE] Renamed `AddConsumer` to `CreateOrUpdateConsumer`. This change is introduced in anticipation for separation of create and update operations in `nats-server` (#1300)
- [BREAKING CHANGE] Change default `AckPolicy` to `AckPolicyExplicit` (#1278)
- [BREAKING CHANGE] Fixed typo in `PullThresholdBytes` type name (#1300)
- [BREAKING CHANGE] Removed push consumer only fields from `ConsumerConfig` (#1300)
- [BREAKING CHANGE] Removed …
=> Release v1.27.0

object.go, test/object_test.go
The `err` variable can be accessed in separate `goroutines` and that causes a race condition. This is demonstrated in the `object_test` file.
It doesn't look like the `err` in the `processChunk` function needs to be the same error used elsewhere in the `Get` method. By creating an `err` variable in the `processChunk` function, there is no race condition anymore.
Close #1313
=> Fix Race condition in object store with nats context

jetstream/pull.go
Previously, the normal inbox was used, which is a security risk in real applications.
Fixes #1307
=> The private inbox of the connection is used.

README.md, nats.go
- JetStream Simplified API:
- Fixed unit from kB to B for `FetchBytes()` in `jetstream/README.md` (#1329)
- Add param names in API interfaces to better document the code (#1316)
- JetStream Simplified API:
- Use custom inbox prefix set on `nats.Conn` for pull requests (#1322)
- Object Store:
- Fixed race condition in object store when `nats.Context` is used (#1314)
- JetStream:
- Fixed creating a consumer with `Durable` not set on server versions prior to 2.9.0 (#1325)
https://github.com/nats-io/nats.go/compare/v1.27.0...v1.27.1
=> Release v1.27.1

jetstream/jetstream.go, jetstream/ordered.go, jetstream/pull.go, jetstream/stream.go, jetstream/test/helper_test.go, jetstream/test/jetstream_test.go, jetstream/test/ordered_test.go
- Previously client was lazily initializing consumer when `OrderedConsumer` was used, but that made `Info()` return an error if invoked before consuming messages
- Added some missing unit tests
=> Create consumer on OrderedConsumer, add missing tests

internal/parser/parse_test.go
This change aligns the input with the name of the test case and ensures that the function is accurately tested with this input.
=> [FIXED] Correct input for "parse 0" test case

context.go, enc.go, encoders/builtin/default_enc.go, encoders/builtin/gob_enc.go, encoders/builtin/json_enc.go, encoders/protobuf/protobuf_enc.go, encoders/protobuf/testdata/pbtest.pb.go, jetstream/api.go, js.go, micro/request.go, micro/service.go, micro/test/service_test.go, nats_test.go, netchan.go, test/helper_test.go, test/js_test.go, test/json_test.go, test/protobuf_test.go
This PR restores changes reverted for patch release in #1330
=> [IMPROVED] Replace empty interface with any

jetstream/message.go, jetstream/options.go, jetstream/test/message_test.go
This cleans up the API a bit, avoiding having a method with a single option to modify the behavior.
Resolves #1299
=> [CHANGED] Move NakWithDelay to separate method

js.go, js_test.go
If an ordered consumer was configured with a start time, on retry, the copied consumer config would start with sequence but the existing start time opt would conflict causing a config error.
Fix #1281
---
Just noting that I added the `StartTime()` opt to the test which, without clearing start time on retry (the fix), it will demonstrate the behavior and get this message:
```
nats: consumer delivery policy is deliver by start sequence, but optional start time is also set: recreating ordered consumer on connection [4] for subscription on "a"
```
=> Unset start time for ordered consumer on retry

jetstream/errors.go, jetstream/jetstream.go, jetstream/message.go, jetstream/options.go, jetstream/publish.go, jetstream/pull.go, jetstream/stream.go, jetstream/stream_config.go
Just fixed some typos in the doc comments and updated doc comments for `Consume()` and `Messages()` with the accepted functional options.
=> Fix typos and doc comments for JetStream simplified API

jetstream/pull.go, jetstream/test/pull_test.go
This is a fix for the issue #1343.
I have included a test showing the issue.
=> JetStream API: Fix `Next()` blocking indefinitely after calling `Stop()`

jetstream/README.md, jetstream/pull.go
=> [FIXED] Invalid heartbeat errors in Consume()

jetstream/README.md, jetstream/jetstream.go, jetstream/options.go, jetstream/stream.go, jetstream/test/jetstream_test.go, jetstream/test/stream_test.go
- `ListStreams` and `StreamNames` now allow for iterating over returned channel (channel is always closed)
- `ListStreams` and `StreamNames` now both accept `WithStreamListSubject` for filtering out returned streams
=> [CHANGED] Simplified API for listing streams and stream names, added option to filter by stream name

jetstream/message.go
Mutex must be unlocked on return from function.
=> Fix deadlock caused by locked mutex

test/js_test.go, test/kv_test.go
This PR fixes 2 frequent flaky tests:
- `TestJetStreamSubscribe_AckPolicy()` - in this test `sub.Drain()` was executed before getting consumer info. Even though `nats.Durable()` option was used in `Subscribe()`, the consumer is still deleted if created by library
- `TestKeyValueMirrorCrossDomains()` - there were races in this test and it sometimes failed if values were not propagated to the mirror before attempting to get them
=> [IMPROVED] Fixed flaky tests in js.Subscribe() and kv

.golangci.yaml, jetstream/errors.go, jetstream/jetstream.go, jetstream/kv.go, jetstream/options.go, jetstream/test/kv_test.go, js.go, kv.go, nats.go, object.go, test/js_test.go, test/sub_test.go
This PR adds the KV implementation to new JetStream API.
This implementation uses ordered push consumer from legacy API to avoid breaking changes in subject permissions. Most of the implementation stays the same, but the API changed to be more in-line with the rest of `jetstream` package (e.g. using context).
=> [ADDED] KV implementation in new JetStream API

jetstream/kv.go, jetstream/test/kv_test.go, kv.go, object.go, test/kv_test.go, test/object_test.go
- Added `UpdatesOnly()` option to object store watchers
- Modify KV watcher behavior for `UpdatesOnly()` so that it does not send `nil` update after creating the watcher
=> [ADDED] UpdatesOnly() option for object store watchers

jetstream/README.md, jetstream/consumer.go, jetstream/ordered.go, jetstream/test/message_test.go, jetstream/test/publish_test.go, js.go, nats_test.go, test/conn_test.go, test/drain_test.go, test/js_test.go, test/object_test.go
Fixes typos in comments and error message found using codespell.
=> [FIXED] typos in comments and error messages

jetstream/test/kv_test.go, test/js_test.go
This PR fixes 2 flaky tests:
- `TestPullSubscribeFetchBatch` somethimes failed on "cancel context during fetch" step because of too short wait before cancellation (messages were not fetched in time)
- `TestListKeyValueStores` failed when 1025 kv stores were not created before context timed out
=> [IMPROVED] Fixed flaky tests

jetstream/jetstream.go
Error handling is repeated twice. this commit omits one of them
=> fix: remove unnecessary error handling

object.go, test/object_test.go
=> [ADDED] Object-store-metadata

nats.go, nats_test.go
=> [ADDED] Invoke ErrorHandler on preparing connection string when reconnecting

nats.go
This adds a default value for flusher timeout, preventing deadlock in certain circumstances
=> [ADDED] Default value for FlusherTimeout

jetstream/options.go, jetstream/ordered.go, jetstream/pull.go, jetstream/test/ordered_test.go, jetstream/test/pull_test.go
Adds the ability to have the consuming of messages automatically be stopped after a certain number of messages is reached (preventing for example the automated fetching to fetch more messages than you need) specified with an AutoStopAfter option. This is the new JS API's equivalent to AutoUnsubscribeAfter() in core NATS (which can be used for push consumers).
=> [ADDED] AutoStopAfter options to Consumer Consume() and Messages()

README.md, nats.go
This release focuses on adding features introduced in nats-server@v2.10.0. Among other things, this includes setting multiple filter subjects for a consumer, configuring stream subject transform, as well as setting stream and consumer metadata.
- JetStream:
- `SubjectTransform` support on streams (#1200)
- `SubjectTransforms` on mirrors and sources (#1359, #1404)
- Multiple subject filters on consumers (#1214)
- Setting `Compression` type on `StreamConfig` (#1405)
- Setting `FirstSeq` on `StreamConfig` (#1405)
- Setting `ConsumerLimits` on `StreamConfig` (#1405)
- `CreateConsumer` and `UpdateConsumer` methods (#1379)
- Support for stream and consumer metadata (#1384)
- ObjectStore:
- Support for object store and object metadata (#1385)
- Service API (`micro`):
-  Customizing queue groups …
=> Release v1.30.0

README.md, nats.go
- JetStream:
- Fixed validation on `nats.PullHeartbeat()` causing pull heartbeat not being validated against deadline from `nats.Context()` (#1414)
=> Release v1.30.1

jetstream/jetstream.go, jetstream/test/jetstream_test.go, jsm.go, test/js_test.go
Server 2.10 now returns source infos (as well as the config) so you can for example tell which sources where successfully added for the stream, and what their current state is) but 2.9 would only return the source config info inside the stream info.
nats.go 2.10 added a check that all of the sources defined in the config where indeed added to the stream in the stream create transform, which would work with a 2.10 server but not with a 2.9.
This fixes the test by downgrading it to the best you can do with a 2.9 server which is check against the stream config returned in the create response message.
=> [FIXED] Stream create response test for sources being present in the response.

jetstream/jetstream.go, jetstream/test/jetstream_test.go
After using JetStream on a private project I felt the need for CreateOrUpdateStream like CreateOrUpdateConsumer. This function updates if stream exists, otherwise it creates the stream.
=> feat: implement CreateOrUpdateStream function

nats.go, test/conn_test.go
This allows to connect to a server that is also configured to perform the TLS handshake first, that is, before sending the INFO protocol.
=> [ADDED] TLSHandshakeFirst option

dependencies.md
=> Format dependencies.md and remove versions

README.md, nats.go
- Core NATS:
- `TLSHandshakeFirst` option to perform TLS handshake before receiving the `INFO` protocol message. **Note**: This option is not yet available in `nats-server` (#1433)
- Test (dev) dependencies are no longer added to `go.mod` when using `nats.go` (#1441)
- JetStream:
- Panic on `Consumer.Info()` when empty response and errors are returned (#1426)
- Invalid handling of heartbeats in `Consume` and `Messages` (#1428)
- Panic on `ConsumerInfo()` when empty response and errors are returned (#1426)
- Fixed typos in `jetstream/README.md` (#1436)
- Updated client dependencies list (#1439, #1440)
=> Release v1.31.0

micro/request.go, micro/service.go, test/compat_test.go, test/configs/docker/Dockerfile
- added compatibility test for service api - complimentary PR in compat-tests: https://github.com/synadia-io/client-compatibility-tests/pull/14
- fixed a bug which caused `asyncDispatcher` to not close properly
- user errors are now reported in stats
=> Compatibility tests for micro

js.go, test/js_test.go
- library now attempts to remove consumer befor creating a new one when resetting ordered consumer
- fixed recreated consumer name to be in the same format as the initial one (short hash of nuid instead of full nuid
=> Remove ordered consumer on reset and fix recreated consumer name

jetstream/options.go
Fixed invalid option validation where pull expiry could be set to < 1s. This bug was only present in `consumer.Messages()`
Fixes #1467
=> [FIXED] Invalid PullExpiry validation

jetstream/options.go, jetstream/publish.go, jetstream/test/publish_test.go
Adds retry logic similar to `Publish()` and `PublishMsg()` to async counterparts. Previously `WithRetryAttempts` and `WithRetryWait` options were ignored.
Fixes #1462
=> [ADDED] Retry PublishAsync on no responders

jetstream/jetstream.go, jetstream/publish.go, js.go
The length of the async pub ack prefix was a constant, while it should no be.
In case of custom inbox prefix, the ID was not properly calculated.
Fortunately it could never lead to out of range issues, but it could increase collision for map id in case of very short inbox prefixes.
=> Fix async publish PAF id

jetstream/pull.go, jetstream/test/ordered_test.go
=> Fix Ordered Consumer for Next

jetstream/kv.go, jetstream/test/kv_test.go, kv.go, test/kv_test.go
Addresses ADR issue: https://github.com/nats-io/nats-architecture-and-design/issues/253
=> [ADDED] Compression option on KV bucket

jetstream/kv.go, jetstream/test/kv_test.go, kv.go, test/kv_test.go
Fixes #1486 
Bug was reported for the new API, but actually it also was present in the old API.
=> Fix prefix in key value stores

jetstream/kv.go, jetstream/test/kv_test.go, kv.go, test/kv_test.go
=> [ADDED] ListKeys method for listing kv keys

jetstream/ordered.go, jetstream/pull.go
Fixes concurrent read/write to subscriptions map
=> [FIXED] Race condition when getting pull subscriptions in ordered consumer

jetstream/jetstream_test.go, jetstream/pull.go
- fixed invalid condition when `s.fetchInProgress` was ignored
- fixed calculating batch size when working with MaxBytes
=> [FIXED] Invalid checkPending logic

jetstream/jetstream.go, jetstream/options.go, jetstream/stream.go, jetstream/test/stream_test.go
This functionality has been available in legacy API but not in the new one. It addresses https://github.com/nats-io/nats-architecture-and-design/issues/153
=> [ADDED] Paging subjects in stream info

micro/test/service_test.go
=> [IMPROVED] Test for concurrently adding service endpoints

jetstream/jetstream.go, jsm.go
This adds reservations to AccountInfo and fixes missing Tiers map in new JetStream API. Reservations on AccountInfo will be available in the next server release.
=> [ADDED] Return account reservations on AccountInfo

README.md, nats.go
- JetStream:
- ObjectStore is now available as part of `jetstream` package (#1450)
- `Drain` method for `ConsumeContext` and `MessagesContext`. Unlike `Stop()`, in addition to unsubscribing and canceling the existing pull requests it will ensure that all messages already stored in client buffer will be available for processing (#1515)
- Return account reservations on `AccountInfo`. **NOTE**: This is only available since nats-server@v2.10.8 (#1511)
- Paging `Subjects` on `Stream.Info()` response when `WithSubjectFilter()` option is used (#1517)
- KeyValue:
- `Compression` option on `KeyValueConfig` (#1451)
- `ListKeys` method for efficiently iterating over all keys in KV bucket (#1490)
- `ResumeFromRevision` option for KV watcher (#1489)
- Fixed and issue where ordered …
=> Release v1.32.0

nats.go
In the examples for establishing secure (TLS) connections to NATS - the README shows using a nats.Secure method - which allows us to pass in a TLS config.
However, the godoc warns against this. @wallyqs informed me that this comment can be removed.
=> docs: safe to use with proper config

jetstream/consumer.go, jetstream/consumer_config.go, jetstream/errors.go, jetstream/jetstream.go, jetstream/jetstream_options.go, jetstream/kv_options.go, jetstream/message.go, jetstream/object_options.go, jetstream/options.go, jetstream/ordered.go, jetstream/publish.go, jetstream/pull.go, jetstream/stream.go, jetstream/stream_config.go
This is the first part of improving `jetstream` package documentation.
This PR updates documantation for core jetstream (no KV or Object Store), by expanding docs to struct fields, as well as having more detailed documentation on public methods and interfaces.
What will be added in subsequent PRs:
- KV/Object store documentation improvements, together with respective section in README
- Code examples
=> Improve `jetstream` documentation

jetstream/object.go, jetstream/test/object_test.go, object.go, test/object_test.go
=> [FIXED] Set read deadline in object store to a configurable value

jetstream/consumer_config.go, jetstream/stream_config.go, object.go
=> [ADDED] Timestamp fields to stream and consumer infos

jetstream/README.md, jetstream/kv.go, jetstream/kv_options.go
=> [IMPROVED] KeyValue documentation

encoders/builtin/default_enc.go, example_test.go, jetstream/stream_config.go, micro/test/service_test.go, object.go, test/conn_test.go, test/js_test.go
=> Fix some typos.

jetstream/consumer.go, jetstream/jetstream_options.go, jetstream/pull.go, jetstream/test/pull_test.go
=> [ADDED] FetchHeartbeat option for Fetch and FetchBytes

js.go
=> [IMPROVED] Add legacy api warnings on old JetStream API

jetstream/object.go, jetstream/test/object_test.go
Similar changes to #1549, only for object store.
I'll be updating the documentation for the whole object store in the next PR.
=> [ADDED] UpdateObjectStore and CreateOrUpdateObjectStore methods

jetstream/README.md, jetstream/object.go, jetstream/object_options.go
=> [IMPROVED] ObjectStore documentation

jetstream/stream.go
This exports `streamConsumerManager` which was used inside `Stream` interface.
This is done so that the interface methods are visible in godoc. Prior to this change, because `streamConsumerManager` is not exported, those methods are available in API but hidden from documentation.
=> [IMPROVED] Export nested ConsumerManager interface

nats.go, test/conn_test.go
This PR adds ability to load TLS config with custom callbacks. Previously it was only possible to either set the whole `TLSConfig` in `nats.Secure()` (which is not reloaded on reconnect) or pass files to `nats.ClientCert()` and `nats.RootCAs()` options.
Adding this function increases flexibility and is consistent with what we do for credentials in `nats.UserJWT()` option.
=> [ADDED] Setting TLS config with callbacks in Connect

object.go
Missing struct tag results in `Compression` with a capital C when serialized
=> Add Missing Compression Struct Tag

nats.go
Using `fmt.Sscanf()` in muxer caused performance overhead for each request sent by the client. It is sufficient to only compare the expected inbox prefix with the response subject and grab the token from the end of the subject (as is done in other clients).
Benchmark results:
1. Using `fmt.Sscanf`: `BenchmarkRespToken-10 2836392 418.7 ns/op 83 B/op 4 allocs/op`
3. Comparing prefixes: `BenchmarkRespToken-10 408571200 2.837 ns/op 0 B/op 0 allocs/op`
Fixes #1560
=> [IMPROVED] Performance of respToken

jetstream/object.go, object.go, test/object_test.go
The change is needed to properly operate on mirrored object store buckets. By binding stream nats.go does not need to search for stream by subjects (which does not work for mirrors).
Related issue: https://github.com/nats-io/nats-server/issues/5106
=> chore: Bind Object Store bucket stream when getting object.

jetstream/object.go, jetstream/test/object_test.go, object.go, test/object_test.go
When mirroring Object Store, there is a need to setup subject transformations. However, client also needs to bind to the stream to avoid stream lookup, which is both not necessary and expensive, and also does not work with Object Store mirrors.
=> Fix Object Store Mirrors

bench/bench.go, bench/benchlib_test.go
Fixed following typos:
.\bench\bench.go:39: agregating ==> aggregating
.\bench\bench.go:159: meessages ==> messages
.\bench\benchlib_test.go:119: througput ==> throughput
=> [FIXED] typos in comments

README.md, nats.go
This release fixes `v1.33.0` release which was re-released with different tag, causing checksum mismatch when running `go get github.com/nats-io/nats.go@v1.33.0`.
=> Release v1.33.1

jetstream/pull.go, js.go, jserrors.go, test/js_test.go
=> [IMPROVED] Fetch and FetchBatch for draining and closed subscriptions

js.go
=> [FIXED] Race condition in Fetch and FetchBatch when using heartbeats

jetstream/publish.go, jetstream/test/publish_test.go, js.go, test/js_test.go
=> [FIXED] Async publish error handling on disconnect

micro/request.go
Allow to check if the request contains a `Reply` subject
Fixes #1579
Signed-off-by: Massimo Costa <costa.massimo@gmail.com>
=> [micro] Add API to read Reply subject from `micro.Request`

nats.go
Signed-off-by: Neil Twigg <neil@nats.io>
=> Remove unnecessary allocations from `readMIMEHeader`

jetstream/kv.go, jetstream/test/kv_test.go, test/kv_test.go
=> [FIXED] KV discard policy in jetstream pkg

jetstream/kv.go, jetstream/test/kv_test.go
=> [FIXED] Add discard policy repair logic in CreateKeyValue

jetstream/consumer.go, jetstream/jetstream.go, jetstream/jetstream_test.go, jetstream/kv.go, jetstream/test/kv_test.go, jetstream/test/stream_test.go, jserrors.go, jsm.go, kv.go, test/js_test.go, test/kv_test.go
=> [FIXED] Validation in jetstream and KV

nats.go, test/conn_test.go
This fixes an issue when `ConnectedCB` is not called when using RetryOnFailedConnect and the first attempt to connect fails but subsequent retry is successful.
Previously `ReconnectedCB` was invoked in such case.
=> [FIXED] Call ConnectedCB with RetryOnFailedConnect when initial conn failed

jetstream/kv.go, kv.go
This PR add json tags to the `KeyValueConfig` struct like the ones already present in `StreamConfig`. 
This is useful when working with KV buckets because currently you need a map or support struct to marshal / unmarshal a  bucket config to / from JSON.
- I used the `StreamConfig` tags as reference.
- I replicated the `omitempty` option for the fields that have it in `StreamConfig`, but a check is needed for the other ones.
=> [UPDATED] Added json tags to KeyValueConfig struct to behave consistently with the StreamConfig one

example_test.go, nats.go, test/conn_test.go, test/helper_test.go, test/reconnect_test.go, test/sub_test.go
Addresses https://github.com/nats-io/nats-architecture-and-design/issues/259
=> [ADDED] Force reconnect

jetstream/jetstream.go, jetstream/ordered.go, jetstream/stream.go, jetstream/test/ordered_test.go
This changes a few things around creating ordered consumers:
- initial ordered consumer creation is now done without retries
- fixed an issue where start seq could be invalid when resetting a consumer which did not receive any messages
- simplified getConsumerConfig()
=> [IMPROVED] Ordered consumer creation and initial config settings

nats.go, nats_test.go
This change addresses issue https://github.com/nats-io/nats.go/issues/1545, opting for trimming any possible trailing slash as opposed to returning an error to the user.
=> [IMPROVED] Trim trailing slash if set on server address which can cause errors during lookup

jetstream/ordered.go, jetstream/test/kv_test.go, jetstream/test/ordered_test.go
=> [FIXED] Panic in ordered consumer

jetstream/ordered.go, jetstream/pull.go, jetstream/test/ordered_test.go, jetstream/test/pull_test.go
=> [ADDED] ConsumeContext.Closed() method for waiting for consume to be closed/drained

README.md, nats.go
- JetStream:
- `CleanupPublisher` method for removing internal JetStream subscription (#1690)
- `ConsumeContext.Closed()` method for waiting for consume to be closed/drained (#1691)
- JetStream:
- Fix deadlock when accessing subscriptions map on a consumer (#1671)
- Fix panic in `OrderedConsumer` (#1686)
- Fix setting deliver policy in `Fetch()` for `OrderedConsumer` (#1693)
- Change `Fetch` and `FetchBatch` client timeout to a higher value (#1689)
- Trim trailing slash if set on server address which can cause errors during lookup (#1654)
- Fixed README.md formatting (#1692)
- Deprecate encoded connections (#1674)
=> Release v1.37.0

js.go, object.go, test/js_test.go
This PR contains following:
1. Added retry logic for jestream async publish using old API
2. retries are controlled by retry wait and retry attempts publish options
3. no responder error is retried
4. pub ack future object is re-used in retries
This PR fixes following issues:
- https://github.com/nats-io/nats.go/issues/1678
=> [IMPROVEMENT] added client retry for jetstream async publish old API

jetstream/jetstream.go, jetstream/jetstream_test.go, jetstream/message.go, jetstream/ordered.go, jetstream/pull.go, jetstream/stream.go, jetstream/stream_config.go, jetstream/test/kv_test.go, jetstream/test/publish_test.go, js.go, jsm.go, micro/test/service_test.go, nats.go, test/cluster_test.go, test/conn_test.go, test/drain_test.go, test/js_test.go, test/kv_test.go, test/sub_test.go, test/ws_test.go, ws.go
errors.New provides more efficiency than fmt.Errorf. 🚀
=> Refactor: Use errors.New instead of fmt.Errorf to improve efficiency

.github/workflows/ci.yaml, nats.go, test/auth_test.go
=> [ADDED] UserInfoHandler for dynamically setting user/password

.github/workflows/dependencies.yaml, dependencies.tpl
The dependencies.md file is important for understanding what linceses are used by nats.go dependencies, however it needed manual operation.
This automates it by creating a PR if go.mod dependencies changed.
=> Automate updating dependencies report

jetstream/kv.go, kv.go
=> [IMPROVE] Mention TTL in the Update function

nats.go, test/sub_test.go
=> [FIXED] Closing connection on max subscriptions exceeded

jetstream/publish.go, jetstream/test/publish_test.go
This fixes an issue in new JetStream API where if maximum number of retries
in `PublishMsgAsync` are reached and the publish failed, done and stall channels
are not closed.
Additionally, this fixes a potential race issue with modifying user msg when publishing.
=> [FIXED] Publish async not closing done and stall channels after failed retries

jetstream/ordered.go, jetstream/test/ordered_test.go
=> [FIXED] Invalid fetch sequence in ordered consumer Fetch and Next after timeout

jetstream/kv.go, jetstream/test/kv_test.go, kv.go, test/kv_test.go
This adds a `WatchFiltered()` method to both kv implementations (legacy and in `jetstream` package).
This PR is a prerequisite to finishing #1711
=> [ADDED] WatchFiltered method on KV

README.md
1. The info about pre go modules is not relevant anymore, so drop it.
2. Extra slashes are not needed before the version suffix, per https://go.dev/ref/mod#go-install. So make it consistent.
Also, not sure if the command to get nats server is needed here at all?
Signed-off-by: Alex Bozhenko <alex@synadia.com>
=> Update installation commands

jetstream/ordered.go, jetstream/pull.go, jetstream/test/ordered_test.go, jetstream/test/pull_test.go, js.go, test/js_test.go
This fixes a race in both new and legacy JetStream API, where for Fetch APIs returning `MessageBatch` there was a race condition when accessing the error.
Fixes #1733
=> [FIXED] Race in MessageBatch

nats.go
- Remove respMap check from **createNewRequestAndSend** as in already done by: **newRespInbox**
- Remove respMap check from **clearPendingRequestCalls** as the for will already check for us: https://go.dev/play/p/FTzU6FRDSnv
=> [FIXED] twice respMap nil check

README.md, nats.go
- Core NATS:
- Added `UserInfoHandler` for dynamically setting user/password (#1713)
- Added `PermissionErrOnSubscribe` option, causing `SubscribeSync` to return `nats.ErrPermissionViolation` on `NextMsg()` if there was a permission error ((#1728)
- Added `Msgs()` method on `Subscription`, returning an iterator (`iter.Seq2[*nats.Msg, error]`) for the subscription. This method is only available for go version >=1.23 (#1728)
-  KeyValue:
- Added `WatchFiltered` method to watch for updates with multiple filters (#1739)
- Core NATS:
- Fixed closing connections on max subscriptions exceeded (#1709)
- Removed redundant nil checks (#1751)
- Add missing nats prefix to error (#1753)
- JetStream:
- Fixed `PublishAsync` not closing done and stall channels after failed retries (#1719)
- Set valid …
=> Release v1.38.0

jetstream/consumer_config.go, jetstream/ordered.go, jetstream/test/ordered_test.go
Id like to set these options for ordered consumers.
=> [IMPROVED] Add extra option to OrderedConsumerConfig

go.mod
=> [CHANGED] Remove toolchain version from go.mod

jetstream/README.md, jetstream/consumer.go, jetstream/jetstream_options.go, jetstream/pull.go, micro/README.md
=> [IMPROVED] Documentation of jetstream options and Fetch clarification

jetstream/object.go, jetstream/test/jetstream_test.go, jetstream/test/kv_test.go, jetstream/test/object_test.go, jetstream/test/ordered_test.go, jetstream/test/stream_test.go, js.go, test/js_test.go, test/kv_test.go, test/norace_test.go, test/object_test.go
=> [FIXED] Fix tests against main server branch

.github/workflows/dependencies.yaml, dependencies.tpl
The `compress` license for the code we use is actually BSD-3, however it's License.md file is confusing the `go-license` tooling.
=> Add exception to `compress` license

jetstream/pull.go, jetstream/test/pull_test.go
This fixes an issue where for `Consumer.Messages` the heartbeat error would be returned after 4*idle heartbeat (instead of 2*)
=> [FIXED] Invalid heartbeat timer for Consumer.Messages

ws.go
Fixes: https://github.com/nats-io/nats.go/issues/1783
This PR addresses a problem that happens when using WS compression and receiving PONGs from the server along with other compressed messages.
The byte slices added to websocketReader.pending are memory references to the original buffer, so when the buffer is re-written in websocketReader.drainPending([]byte) the value for the pending PONG message takes a value that is part of the re-written bytes in the buffer.
This only happens with compression, because the size of the messages in the buffer changes, and only happens when receiving PONG messages, because the value for the regular messages is a new []byte generated after decompression, and not a memory reference to a sub-slice of the original buffer
=> fix: protocol parsing errors with ws compression and pongs

jetstream/jetstream.go, nats.go
=> [FIXED] Protect against possible nil pointer panic

jetstream/api.go, jetstream/consumer.go, jetstream/jetstream.go, jetstream/jetstream_options.go, jetstream/kv.go, jetstream/message.go, jetstream/ordered.go, jetstream/publish.go, jetstream/pull.go, jetstream/stream.go, jetstream/test/jetstream_test.go
=> [ADDED] Options() and Conn() methods to JetStream

jetstream/README.md, jetstream/errors.go, jetstream/jetstream_options.go, jetstream/message.go, jetstream/pull.go, jetstream/test/pull_test.go
This PR adds a new option to be used with `Consumer.Consume` and `Consumer.Messages` - `PullMaxMessagesWithFetchSizeLimit`. This option sets both max messages and max bytes in each fetch request, but does not track pending bytes and always sends constant `max_bytes` in each pull request.
=> [ADDED] PullMaxMessagesWithFetchSizeLimit option for Consume and Messages

jetstream/README.md, jetstream/jetstream_options.go
=> [IMPROVED] Enhance documentation for PullMaxMessagesWithBytesLimit and PullMaxBytes

README.md, nats.go
This release bumps the minimal go version in `go.mod` to `1.22`.
- JetStream:
- Added `PullMaxMessagesWithFetchSizeLimit` option for Consume and Messages (#1789)
- Added `Metadata` to `OrderedConsumerConfig` (#1737)
- Added `JetStream.Options()` and `JetStream.Conn()` methods to `JetStream` interface (#1792)
- KeyValue:
- Added `ListKeysFiltered` for listing keys with multiple filters (#1711)
- JetStream:
- Fixed invalid heartbeat timer for `Consumer.Messages()` (#1786)
- ObjectStore:
- Fixed invalid error being returned from `DeleteObjectStore` (#1762)
- WebSockets:
- Fixed protocol parsing errors with websocket compression and PONGs (#1790)
- Core NATS:
- Protect against possible nil pointer panic (#1771)
- Bump go version to v1.22 (#1773)
- Fixed typo in JetStream docs (#1758)
- …
=> Release v1.39.0

jetstream/kv.go, jetstream/test/kv_test.go
https://github.com/nats-io/nats.go/issues/1802
=> Prevents KV ListKeysFiltered from returning deleted keys

js.go, jserrors.go
An ordered consumer would not be recreated if there's temporarily no meta leader, which returns the following error:
```
nats: JetStream system temporarily unavailable: recreating ordered consumer on connection [70] for subscription on ""
```
After the first error, it will continuously fail with a `nats: invalid subscription` error.
That error matches with this server error:
```
JSClusterNotAvailErr: {Code: 503, ErrCode: 10008, Description: "JetStream system temporarily unavailable"},
```
=> [FIXED] Invalid subscription on ordered consumer in leaderless cluster

jetstream/publish.go, js.go
=> [FIXED] Avoid ack id collision in PublishAsync

jetstream/pull.go
=> [FIXED] Possible panic in Consumer.Fetch

jetstream/stream.go
The error message in deleteMsg was printing nil when resp.Success was false. Changed to use resp.Error, displaying the actual NATS error.
=> fix: use resp.Error to show NATS error in deleteMsg

kv.go, test/kv_test.go
KV watcher will now send a `nil` marker if we've not reached 0 pending msgs and have not received any new key for more than JS timeout. This avoids a deadlock when messages are purged/deleted from the stream while e.g. listing keys.
=> [FIXED] Deadlock when fetching keys from KV while messages are deleted/purged

micro/README.md, micro/service.go, micro/test/service_test.go
Signed-off-by: Piotr Piotrowski piotr@synadia.com
=> [ADDED] Support for disabling queue groups at service, group, and endpoint levels

nats.go, test/conn_test.go
Hi,
I am often using those connect options due to an offline first approach:
```go
opts := []nats.Option{
nats.RetryOnFailedConnect(true),
nats.MaxReconnects(-1),
}
```
I noticed that **none** of the current handlers covers handling connection attempt errors when there never was an initial connection with those options.
This is probably a very narrow use case.
That is why I thought adding `ReconnectErrCB` and the corresponding `ReconnectErrHandler` makes sense.
Since this is my first contribution, please let me know whether I missed something or whether it should be solved
in a complete different manner. I am willing to put in more work if necessary of course.
Sorry for having a bit of additional diffs due to using `gopls` formatting. I did not find any formatting rules.
If there are any, …
=> [ADDED] ReconnectErrCB + handler function

README.md, nats.go
This release focuses on adding support for new features from [NATS Server v2.11.0](https://github.com/nats-io/nats-server/releases/tag/v2.11.0). This includes:
- Per message TTLs
- Consumer pause and resume
Batch direct get will be released in [orbit](https://github.com/synadia-io/orbit.go). Support for consumer priority groups will be added in the next minor release.
- JetStream:
- Pause and resume JetStream consumer (#1571)
- Per message TTL option for JetStream publish (#1825)
- Timeout option for async publish (#1819)
- Service API
- Support for disabling queue groups at service, group, and endpoint levels (#1797)
- Core NATS:
- `ReconnectErrCB` for handling failed reconnect attempts in a callback (#1804)
- JetStream
- Invalid subscription on ordered consumer in leaderless cluster …
=> Release v1.40.0

README.md, nats.go
This release fixes an issue in legacy JetStream `Subscribe` which did not respect user-set context when creating a consumer.
- Set context from option when creating consumer in js.Subscribe (#1835)
=> Release v1.40.1

nats.go, test/reconnect_test.go
Set the `rqch` channel to `nil` after closing to avoid `close of closed channel` panic.
This channel is recreated in `doReconnect()` allowing to bypass wait time between reconnects.
=> [FIXED] Reset channel after closing in ForceReconnect

nats.go
This is a follow-up to #1842 which introduced an issue where `nc.rqch`
could be cleared before reading it in `doReconnect`.
This happened e.g. when an auth error triggered reconnect close to
calling `ForceReconnect` (made apparent by `TestAuthExpiredForceReconnect`
starting to be flaky).
=> [FIXED] Initialize rqch channel for immediate reconnection on ForceReconnect

jetstream/jetstream.go, jetstream/jetstream_options.go, jetstream/test/publish_test.go
This adds a `WithDefaultTimeout` option when creating `JetStream`. This timeout is used when a context without deadline is passed to JetStream requests.
=> [ADDED] DefaultTimeout option for JetStream API requests

README.md, nats.go
This release adds consumer priority groups to JetStream, exposing overflow and pinning policies. For more information on consumer priority groups, see [ADR-42](https://github.com/nats-io/nats-architecture-and-design/blob/main/adr/ADR-42.md).
- JetStream:
- Consumer priority groups with pinned and overflow policies (#1826)
-  `WithDefaultTimeout` option for JetStream API requests (#1843
- KeyValue:
- Ensure timer is stopped when watcher is stopped (#1838)
- ObjectStore:
- Ensure object watcher stop closes the updates channel (#1844)
- Core NATS:
- Data race when reading current status in `sub.StatusChanged` and `nc.StatusChanged` (#1841)
- Reset channel after closing in `ForceReconnect` to avoid panic on subsequent `ForceReconnect` calls (#1842, #1846)
- Cancel `Fetch` …
=> Release v1.41.0

jetstream/object.go
=> [FIXED] Use default timeout for ObjectStore.Get when no deadline is set on ctx

README.md, nats.go
- ObjectStore:
- Use default timeout for `ObjectStore.Get` when no deadline is set on ctx (#1850)
- Remove `golang.org/x/text` dependency (#1849)
=> Release v1.41.1

js.go, nats.go, test/conn_test.go
This adds a new method, `Conn.RemoveStatusListener`, which allows to manually remove an unwanted status changed listener. Internally listeners were converted to map for more efficient lookup.
Fixes a memory leak in `Fetch` and `FetchBatch` which caused status listeners to never be cleaned up (they would only disappear after status is changed).
=> [FIXED] Add RemoveStatusListener method and fixFetch memory leak

nats.go, test/nats_test.go
Currently, the Go client library exposes the remote address of the underlying net.Conn.
It would be helpful if it also exposed the LocalAddr.
The usecase is to help determine which network was used to reach the remote NATS server.
=> Add nc.LocalAddr, similar to nc.ConnectedAddr

micro/service.go
Fixes the issue describe in #1871  by ensuring the ranging of endpoints is not impacted by the action to perform the stop on the endpoint (which manipulates the endpoints slice). This is achieved by making a copy of the slice beforehand.
=> [FIXED] Stopping micro service should fully unsubscribe (#1871)

micro/service.go
=> [FIXED] Remove Println from Service API Stop()

jetstream/stream.go
The (new) JS stream info API would log the following in the server:
```
Invalid JetStream request '$G > $JS.API.STREAM.INFO.<KV_bucket_name>': json: unknown field "total"
```
This was due to the inclusion of the `total` field. Should use the `apiPagedRequest` instead. Current 2.11 servers log this warning, and requests will be fully rejected if strict mode is turned on (which might become the default for 2.12).
=> Fixed stream info request for strict mode

nats.go, test/nats_test.go
Fixes #1873
Allows passing JWT and seed credentials as byte slices instead of file paths.
Mirrors UserCredentials() but accepts bytes directly. Supports both separate 
JWT/seed bytes and chained credential format.
Co-authored-by: @AsyncLegs
=> [ADDED] UserCredentialBytes() option

jetstream/jetstream.go
When creating or updating a stream, the sources in the server response will not be ordered, but the current code assumes so. The commit removes that assumption.
Fixes #1906
=> [FIXED] Fix subject transform comparison

jsm.go, test/js_test.go
Legacy JetStream API calls could block indefinitely if `nats.Context` was used without deadline. This PR changes this so that a timeout from JetStreamContext will be used instead.
=> [FIXED] Use timeout from JetStreamContext if no deadline is set on ctx

jetstream/README.md, jetstream/consumer.go, jetstream/consumer_config.go, jetstream/errors.go, jetstream/jetstream.go, jetstream/jetstream_options.go, jetstream/message.go, jetstream/ordered.go, jetstream/publish.go, jetstream/pull.go, jetstream/push.go, jetstream/stream.go, jetstream/test/consumer_test.go, jetstream/test/jetstream_test.go, jetstream/test/ordered_test.go, jetstream/test/pull_test.go, jetstream/test/push_test.go, jetstream/test/stream_test.go
This PR introduces a `PushConsumer` implementation in jetstream API. For now it only exposes callback-based `Consume()` implementation.
Due to interface differences and breaking change concerns, a completely new set of methods were added to enable operating on push consumers.
=> [ADDED] PushConsumer implementation in jetstream package

README.md, nats.go
This PR adds a `PushConsumer` implementation to `jetstream`, allowing easier migration to new API while maintaining usage of push consumers. For now it only supports the callback-based `Consume()`, more consuming options will be added in future releases.
- Core NATS:
- `UserCredentialBytes()` `Conn` option (#1877)
- JetStream:
- `PushConsumer` implementation in `jetstream` package 
- Expose `ClientTrace` in `JetStreamOptions` (#1886) 
- Service API:
- Expose `WithEndpointPendingLimits` option (#1899)
- Legacy KeyValue:
- `Error()` method to `KeyLister` and `KeyWatcher` interfaces (#1889)
- Core NATS:
-  Fix timeoutWriter not recovering after first error (#1896)
- JetStream:
- `Consumer.Next()` hangs after connection is closed (#1883)
- Fixed stream info request for strict mode (#1887)
- …
=> Release v1.44.0

jetstream/jetstream_options.go, jetstream/message.go, jetstream/publish.go, jetstream/test/publish_test.go
This utilizes the Nats-Expected-Last-Subject-Sequence-Subject header that became available in 2.11.0.
Signed-off-by: Byron Ruth <byron@nats.io>
=> Add WithExpectLastSequenceForSubject publish option

README.md, nats.go
- Core NATS:
- `WithExpectLastSequenceForSubject` publish option (#1920)
- JetStream:
- Handling for maximum account active connections exceeded (#1921)
- Core NATS:
- Track delivered count and auto-unsubscribe for channel subscriptions (#1913)
- Clear status listeners map on `SubscriptionClosed` event to prevent race condition (#1914)
- Call `ReconnectErrHandler` for initial connection failures with `RetryOnFailedConnect` (#1915)
- JetStream:
- `CreateOrUpdateStream` preserves domain prefix during updates (#1917)
- Handle empty response when creating a consumer (#1912)
- KeyValue:
- Add test checking KV TTL watcher updates (#1916)
https://github.com/nats-io/nats.go/compare/v1.44.0...v1.45.0
=> Release v1.45.0
