nats-io/nats.go

parser.go

It was showing up twice on Godoc.

Remove duplicate package comment

---

examples/nats-sub.go

Index was incremented but never used

removed unnneed variable index.

---

nats.go

Remove unused function serversAvailable()

---

nats.go
test/conn_test.go
test/sub_test.go

Fix incorrect ErrConnectionClosed errors

---

nats.go
test/cluster_test.go
test/conn_test.go

/cc @kozlovic 
Can you create an ordered test, possibly pulling from your other PR?

Preserve ordering of callbacks, fixes #30

---

enc_test.go
nats_test.go

Specify different ports for package tests.

Fix test for parallel run.

---

enc_test.go
nats_test.go
parser.go

This was already present in the server.

Optimize for larger messages.

---

netchan.go

Check closed state and send into async cb channel under conn's lock.

Fix netchan encoder's call to async err callback.

---

nats_test.go
parser.go

- Was using wrong 'scratch' field
- Improved test to check for msg content

Fix parser bug introduced in #139

---

test/netchan_test.go

PR #149 had a fix to schedule async err cb within connection's lock.
Without this change, and running the following 10 times:
go test -race -v -cpu=1,2,3,4 -run=TestFailedChannelSend ./...
would produce a data race. With the use of locking, you won't get the race.

Udpate test to capture RACE that would occur without conn's lock.

---

nats.go
test/sub_test.go

instead of ChanQueueSubscribe()
- Added test to check total number of messages do not exceed total.

Fix QueueSubscribeSyncWithChan() which was behaving like ChanSubscribe()

---

nats.go
nats_test.go
test/auth_test.go
test/cluster_test.go
test/conn_test.go

- Trim quotes and convert to lower case before processing error
- Fix parse of error test to just check parser state
- Add two tests to check for stale connection and other error
- Check expected authentication failure error message on connect

Fix processing of error coming from server.

---

README.md
nats.go

Minor documentation updates regarding usage of `LastError()` in case they might be useful.

Add `nc.LastError()` usage to readme, doc updates

---

nats.go
test/sub_test.go

Reject 0 values, but allow negative values to indicate that the
given metric should not be limited.
Resolves #183

Fix SetPendingLimits()

---

nats.go
test/sub_test.go

All variants of Chan subscribers would stop receiving messages
after more than 65536 messages or 65536*1024 bytes. This was
because on processing of a message, the pending counts were
incrememted but never decremented, which would lead to further
messages to be dropped. We no longer update the pending counts
for ChanSubscriptions since they are not relevant.
/cc @derekcollison 
Resolves #193

Fix Chan subscribers inability to receive more than 65536 msgs

---

examples/nats-bench.go

Update nats bench to provide better performance metrics

---

bench/bench.go
bench/benchlib_test.go
examples/nats-bench.go

[NEW] Added 'bench' package to nats
[NEW] Added support for saving samples in CSV format
[NEW] Added tests to bench package
[CHANGED] nats-bench to use bench package
[CHANGED] Format printed in stdout to be simpler

Refactored nats-bench functionality to a small library

---

test/sub_test.go

The test was incorrectly testing only one type of Chan subscription.
Related to #194

[FIXED] TestChanSubscriberPendingLimits

---

nats.go
nats_test.go

The recent change in processing of INFO protocol changed that
behavior by shuffling the entire pool. Now ensure that if Opts.Url
is set, it is first in the array.

[FIXED] If Options.Url is set, try it first on initial connect

---

bench/bench.go

Previous version of the code formatted differently. Some dead logic remained behind.
@mcqueary @kozlovic

Removed dead code from previous iteration.

---

nats.go
test/conn_test.go

[FIXED] LastError Data Race

---

nats.go
test/conn_test.go

The Golang [Dialer](https://golang.org/pkg/net/#Dialer) has a number of options which would be convenient to allow users customizing them.
This changeset adds a `nats.Dialer` func for setting custom dialers (e.g. to activate opt-in `DualStack` support) which would be used when attempting to establish a connection to the server, still using by default the [DialTimeout](https://golang.org/pkg/net/#DialTimeout) behavior as it is currently.

Add option for allowing custom Dialers

---

nats.go
nats_test.go

Returns a string array of all known servers including those updated by the async INFO protocol.

[ADDED] Add Conn.Servers API

---

README.md

Fix connect API usage in example code

---

.travis.yml
nats.go

Adds more documentation to the exported options from the client.

Add comments to exported Options from client which can be customized

---

README.md

Fix typo in message assignment from channel read [ci skip]

---

.travis.yml
test/auth_test.go
test/basic_test.go
test/cluster_test.go
test/conn_test.go

Also added misspell check and updated Go versions in .travis.yml

Update tests following auth changes in gnatsd

---

nats.go

When a client sends data and has at least a matching subscriber,
there may be a case where the flusher is holding the connection's
lock while trying to flush the write buffer, which cannot complete
because the server is not draining data at the moment since it is
itself trying to send data to the client, which processMsg() function
is waiting on the connection's lock. After 2 seconds, the server
will close the client connection.
Using a dedicated lock for the subscriptions map that processMsg
needs to access is reducing the risk of lock contention between
publish/flusher and the readloop's processMsg function.
There would still be a case where if the subscription in the client
is considered a slow consumer and messages are dropped, we need to
acquire the connection lock there. But in …

Reduce risk of server closing conn (slow consumer) if sending to itself

---

nats.go

Statistics are updated either under Conn.mu or Conn.subsMu. Instead
of using atomics when updating the stats and when getting them,
simply lock both Conn.mu and Conn.subsMu in Conn.Stats().
This saves 2 atomic operations on publish and 2 on processMsg.
Related to #285

Remove atomic usage for connection statistics

---

nats.go

This changes the flusher channel to be based on sending empty structs of size 0 for signaling instead of using `chan bool`.

Use empty struct for signaling flusher

---

nats.go
test/cluster_test.go

Also removed extraneous delete(tmp, curl).

Set required gnatsd version to 1.0.7 for test related to async INFO

---

test/json_test.go

Validate encoding/decoding of arrays, empty arrays, null (nil), true (bool), empty strings on the go client.

Added additional JSON tests,

---

GOVERNANCE.md
MAINTAINERS.md
OWNERS

Add GOVERNANCE.md
Update and Rename OWNERS to MAINTAINERS.md

Add Governance/Maintainers [ci skip]

---

test/context_test.go

There were some context usage related failures in Travis due to timing issues:
```
--- FAIL: TestOldContextRequestWithTimeoutCanceled (0.03s)
context_test.go:141: Expected request with timeout context to fail: %!s(<nil>)
```
https://travis-ci.org/nats-io/go-nats/jobs/412394490#L693
In order to prevent this, added an extra wait to the context tests that assumed that the context cancellation was already propagated.

Fix for flapping context tests

---

examples/nats-bench.go

Start the timer only when the first message is received

Fixed nats-bench subscription's start time

---

nats.go

[FIXED] Doc of API creating subscriptions [ci skip]

---

test/basic_test.go
test/conn_test.go
test/netchan_test.go
test/sub_test.go

Fixing some flapping tests

---

context.go
nats.go
test/bench_test.go

Also bumped to 1.7 due to nkeys support.

Faster and smaller reply suffix

---

nats.go
nats_test.go

Added test for NkeyOptionFromSeed

---

examples/nats-bench/main.go

Add support for NGS credentials

NGS Updates

---

README.md

Add import stament to example in README

---

context.go
nats.go
test/context_test.go

Added FlushWithContext(), fixes #431

---

nats.go

#435 I need to reopen a PR because of force-pushed.

Use RWMutex in some simple cases

---

test/json_test.go

This PR corrects ut description more detailed.

make test case description more descritable

---

nats.go
nats_test.go

We were using range but range seems to not be random from a distriution standpoint.

Properly randomize multiple adders for single host.

---

examples/nats-bench/main.go
examples/nats-echo/main.go
examples/nats-pub/main.go
examples/nats-qsub/main.go
examples/nats-req/main.go
examples/nats-rply/main.go
examples/nats-sub/main.go

This PR will refactor examples in 
* Enhance `Usage` function to print default flag settings info in `-h` output
* Remove redundant address reference

refactor examples

---

test/context_test.go

Test for #404

---

go.mod
go.sum

Updated go.mod

---

nats.go
nats_test.go

https://github.com/nats-io/nats-server/issues/84

Check bad subjects and queues on subscribe

---

nats.go

wipe memory again using jwt lib

---

nats.go
nats_test.go

Original test was flaky (and likely not produced proper sequence) on Travis and slower local Linux VM. Adding tracing we would see that the client keeps getting async -ERR auth expired errors. This is because the JWT is considered valid on each (re)CONNECT - even though it has expired - but server will then "immediately" send the expired error from timer's callback. The issue I believe is that JWT lib considers the JWT expired only if expires time > "now" with a mix of Unix() 1 sec granularity.
Removing the NATS Server/JWT from the test makes the test deterministic and actually test the library, not the server handling of expired JWTs...

Trim "nats: " before invoking processErr in doReconnect

---

nats.go
test/drain_test.go

Noticed this on nats-echo example.

Do not hang closed callbacks when Drain() called in reconnecting state

---

examples/nats-qsub/main.go

similar to output in corresponding examples in other languages

[FIXED] Print queue name in example

---

CODE-OF-CONDUCT.md

[ADDED] Missing code of conduct file

---

README.md
nats.go

Release v1.9.2

---

nats.go

Change default flush timeout to 10s

---

nats.go
nats_test.go

Added in support for client IP from the server and RTT calculation

---

parser.go

[FIXED] Bump default max control size to 4K

---

nats.go

Super minor fix that I noticed while working on a NATS app :+1: 
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>

Minor docstring fix on PublishRequest

---

nats.go
nats_test.go
test/sub_test.go

This will be invoked when the server enters LDM mode.

[ADDED] LameDuckModeHandler option/setter

---

MAINTAINERS.md

[CI-SKIP]
Update to MAINTAINERS.md base on newly adopted Governance and Maintainership definitions.

Update MAINTAINERS.md  [ci-skip]

---

enc.go

Small fix that I thought of while encoding my connection using Protocol Buffers 👍

Updated nats.Handler documentation to make it generic to all encoders

---

.travis.yml

PR for the server here: https://github.com/nats-io/nats-server/pull/1593

Add Go 1.15 to CI

---

go.mod
go.sum
jetstream.go
jetstream_test.go
nats.go

add JetStream ack helpers

---

jetstream.go
jetstream_consumer.go
jetstream_test.go
nats.go
nats_test.go

Allow the Subscribe functions to access JetStream consumers

---

nats.go
nats_test.go
test/basic_test.go
test/helper_test.go

expose additional info line information to the client

---

go.mod
go.sum
jetstream_consumer.go
jetstream_test.go

support consumer MaxAckPending

---

test/js_test.go

Fixes imported stream and adds export to test ack of ack when using consumers with direct mode/no api access.

jetstream: Fix AckSync test using import

---

js.go
test/js_test.go

Trying to ack a non JS msg would panic and hang

---

js.go
test/js_test.go

Add in StreamInfo

---

js.go
test/js_test.go

Make file storage the default, implementation for  #623

---

js.go

This changes some of the internals of how functional options are used so that it gives more flexibility when growing the number of options in the client.
The API stays the same but instead of options being concrete types, `PubOpt`, `SubOpt` and `JSOpt` are interfaces so that the behavior changes depending on where an option is used.     
This has a few benefits I think, for example `nats.MaxWait` currently looks like this:
```go
func MaxWait(ttl time.Duration) PubOpt { ... }
```
it can only be applied to publishing, and we also have a similar option for waiting for responses from the API:
```go
func APIRequestWait(wait time.Duration) JSOpt { ... }
```
These are both very similar options about setting a timeout, so with the changes in this PR we can now do:
```go
// MaxWait for responses …
```

js: Treat JS functional options as interfaces

---

js.go
test/js_test.go

Adds `DeleteMsg(name string, seq uint64)` to JetStream management to be able to [erase a message](https://github.com/nats-io/nats-server/blob/b048b6b3dea67ba00a36b713226a3db7dcb48bfb/server/jetstream_api.go#L1025-L1056).

Add DeleteMsg to JetStream management

---

js.go
test/js_test.go

js: Add Subscribe option for AckPolicy

---

js.go
jsm.go
test/js_test.go

js: Add AccountInfo to JetStreamManagement

---

jsm.go

Fix for account info errors

---

js.go
test/js_test.go

This would allow regular subscribers to `Ack()` messages with a reply from JetStream.

js: Allow Acking of JS messages without JS context

---

js.go
nats.go
test/js_test.go

This adds logic to the client so that some type of consumers can be cleaned up depending on whether `Unsubscribe` or `Drain` are called:
```go
// Deletes a consumer (both ephemeral and durables)
sub.Unsubscribe()
// Does not delete durable consumers, but ephemerals are deleted.
sub.Drain()
```
This also means that both `nc.Drain` would also clean up any ephemeral consumer that was created, but not doing anything to durable consumers that were created or attached.
This way in case a durable is created and then an application restarts when it reattaches to the same durable consumer, it can still delete the consumer that it created with `Unsubscribe` or gracefully close using `Drain` without deleting durable consumers.

js: Cleanup of JS consumers on unsub/drain

---

js.go
jsm.go
nats.go
test/js_test.go

js: Add GetMsg API to JetStreamManager

---

go.mod
go.sum
test/js_test.go

js: Update server, add test of updating a stream with sources

---

js.go
test/js_test.go

This adds a `nats.Stream` option that can be used to set stream from where messages can be consumed. 
```go
js.SubscribeSync("origin", nats.BindStream("mirror"))
js.SubscribeSync("origin", nats.BindStream("source"))
```
Signed-off-by: Jaime Piña <jaime@synadia.com>

js: Add option to consume from Streams that are mirrors or sourced

---

.travis.yml
go.mod
go.sum
test/js_test.go

js: Update server dependency, use Go 1.16 in Travis

---

test/js_test.go

Add test for PullSubscribe and types of acks

---

js.go
jsm.go

This adds documentation to methods that were missing it. In addition, it also fixes some minor comment mismatches. I also did a little bit of tweaking to existing doc.

Update API doc

---

js.go

`PubAckFuture` could work well as interface type returned for the user since the behavior is controlled by the `nats` package and only internal fields, in the library we will use the concrete version of the type. This would prevent users create their own future that cannot be initialized `fut := nats.PubAckFuture{}` and allows testing of handling publishes under failing conditions for example:
```go
type badPubAck struct {
err error
}
func (paf *badPubAck) Ok() <-chan *nats.PubAck {
return nil
}
func (paf *badPubAck) Err() <-chan error {
errCh := make(chan error, 1)
errCh <- fmt.Errorf(`nats: no responders`)
return errCh
}
func (paf *badPubAck) Msg() *nats.Msg {
return nil
}
func processPubAck(paf nats.PubAckFuture) error {
select {
case err := <-paf.Err():
fmt.Printf("Got: %v\n", err) …
```

js: PubAckFuture as interface

---

go.mod
go.sum
test/js_test.go

Update nats-server test dependency to 2.2.1

Update nats-server test dependency to 2.2.1

---

example_test.go
js.go
test/js_test.go

Add consumer to msg Metadata

---

nats.go

Fix to ping/pong processing

---

js.go

This makes the pull based subscription have their own requests handler to make fetch requests using a single wildcard subscription similar to how `nc.Request` works. Unlike `nc.Request` though, it does not use a token to identify response to requestor since the inbox gets rewritten when the JS message is delivered, and just sends the latest response to the first available requestor.

js: Add async sub for PullSubscribe to make fetch requests

---

example_test.go
js.go

Add godoc example for JS context functions

---

nats.go
test/basic_test.go

Check for no responders error in sub.NextMsg

---

README.md

Move the JetStream example code toward the top of README.md.

Move JetStream Examples

---

README.md

Update badges urls/etc..

---

README.md
nats.go

Release v1.12.2

---

README.md
nats.go

Release v1.12.3

---

js.go

JetStream: revert some change made to ordered consumer

---

test/reconnect_test.go

Add test case to document usage of disabling reconnect buffer.

Add test that disables reconnect buf

---

README.md
nats.go

Release v1.14.0

---

README.md
go_test.mod
go_test.sum
nats.go

Release v1.16.0

---

js_test.go
jsm.go
kv_test.go

Mirrors can answer direct gets potentially so removing error condition.

---

jserrors.go
test/js_test.go

js: remove api error code from description

---

README.md
nats.go

- KV:
- Support for KV mirrors and sources (#1112)
- JetStream:
- Comment on `InactiveThreshold` to align with server version 2.9.0. Thanks to @neilalexander for the contribution (#1106)
- Added Service framework for microservice communication using core NATS. This is an experimantal preview and may be changed in future releases (#1111)
https://github.com/nats-io/nats.go/compare/v1.18.0...v1.19.0

Release v1.19.0

---

README.md
nats.go

- JetStream:
- Expose `StreamNameBySubject` method on `JetStreamContext` interface for looking up stream by subject (#1114)
- Return stream alternates when fetching stream info (#1118) 
- KV:
- Use BindStream for watcher so it works with mirrors (#1116) 
- KV:
- Delete key not working correctly across mirrors (#1115)

Release v1.19.1

---

README.md
nats.go

This release adds a beta implementation of `micro` package, which provides API for creating and monitoring microservices on top of NATS  connection.
- Service API beta implementation (#1160)
- Getters for connection callbacks (#1162)

Release v1.22.0

---

micro/service.go
micro/service_test.go

Update for https://github.com/nats-io/nats-architecture-and-design/pull/183

Adds response data types for latest ADR update

---

README.md
nats.go

This release focuses on improvements in `micro` package, most notably adding a possibility to create a service with multiple endpoints.
- Service API (`micro`):
- Support for multi-endpoint services (#1180)
- `type` field in monitoring handlers responses (#1173)
- JetStream:
- Optimize `AddConsumer()` performance by not sending JS request if consumer config has not changed (#1185)
- Service API (`micro`):
- Use interface instead of struct for `micro.Request` (#1174)
- Use `time.Time` instead of `string` for `Started` field in `STATS` response (#1175)
- Service schemas are now defined per-endpoint. 
- Check whether credentials in `nats.Connect()` are missing before using them (#1181)
- Reduce the size of the bufio.Reader for message header parsing (#1187)
- Update go version in `go.mod` to …

Release v1.23.0

---

micro/service.go
micro/test/service_test.go

avoid panic on schema request when no schemas were given

---

js.go
js_test.go
test/js_test.go

[ADDED] FetchChan method to utilize non-blocking pull subscription requests

---

kv.go

Set AllowDirect for upgrades from prior to 2.9.x

---

jserrors.go
jsm.go
test/js_test.go

Resolves https://github.com/nats-io/nats.go/issues/1218

[FIXED] Stream and consumer name validation

---

js.go
jserrors.go

Resolves https://github.com/nats-io/nats.go/issues/1216

[FIX] Retry recreating ordered consumer on insufficient resources error

---

README.md
nats.go

- Core:
- Option to skip host lookup (#1204)
- JetStream
- `FetchBatch` method to utilize non-blocking pull subscription requests (#1211)
- Service API (`micro`):
- `ContextHandler` helper function which implements `micro.Handler` and allows passing `context.Context` to request handler (#1215)
- Use go 1.19 in `go.mod` and skip using deprecated `rand.Seed` for go version +1.20 (#1209)
- JetStream:
- Retry recreating ordered consumer on insufficient resources error (#1217)
- Stream and consumer name validation now checks for space in name, preventing timeouts and returning valid error (#1219)
- Service API (`micro`):
- Avoid panic on schema request when no schemas were given (#1195)
- KV:
- Fix `CreateKeyValue` idempotency check on `AllowDirect` when upgrading server version to > 2.9.0 …

Release v1.24.0

---

README.md
nats.go

- Service API (`micro`):
- Support metadata for services, endpoints and endpoint stats (#1231, #1233)
- Fix `TestJetStreamStreamInfoWithSubjectDetails` test (#1225)
- Fix typo in JetStream `Durable()` option comment (#1229)
- Bump nkeys to latest version (#1235)
- JetStream:
- Use wildcard subscription for pull subscription and separate inbox per `Fetch()`/`FetchBatch()`. Additionaly, `FetchBatch()` now
verifies whether a request timeout was received for a current pull request (#1237, #1238)

Release v1.25.0

---

nats.go

In preparation to fixing https://github.com/nats-io/kubecon-contribfest/issues/10

introduce new options builder for transitioning to the new Connect API

---

go_test.mod
go_test.sum
test/conn_test.go
test/headers_test.go
test/js_test.go
test/main_test.go

- fix instances of leaking goroutines in tests
- add [goleak](https://github.com/uber-go/goleak) as a dependency and verify tests for leaking goroutines

[FIXED] Leaking goroutines in tests

---

README.md
nats.go

This release adds beta functionality of JetStream simplified API. The goal of this API is to simplify and streamline stream and consumer management, as well as leverage pull consumers for continuous message retrieval. We encourage you to give it a try and post your feedback!
You can find more details on the new API [here](https://github.com/nats-io/nats.go/blob/main/jetstream/README.md)
- JetStream Simplified API:
- This new API overhauls whole nats.go JetStream API and will eventually deprecate the legacy JetStream client implementation. For details, visit README.md in `jetstream` directory (https://github.com/nats-io/nats.go/blob/main/jetstream/README.md) (#1273 ).
- JetStream:
- `ConsumerName()` subscribe option to set `Name` in `ConsumerConfig` when creating a consumer (#1263)
- …

Release v1.26.0

---

jetstream/pull.go

This PRs simplifies mutex usage in pull consumer JetStream API

[IMPROVED] Lock handling for pull consumers

---

example_test.go
go_test.mod
go_test.sum
jetstream/consumer.go
jetstream/errors.go
jetstream/test/stream_test.go
js.go
jserrors.go
jsm.go
test/js_test.go

Addresses https://github.com/nats-io/nats-architecture-and-design/issues/196

[ADDED] Support for multiple subject filters on consumers

---

jetstream/consumer_config.go

[IMPROVED] Add note about required server version for FilterSubjects in ConsumerConfig

---

jsm.go

[FIXED] Creating ephemeral consumers on server < 2.9.0

---

context.go
enc.go
encoders/builtin/default_enc.go
encoders/builtin/gob_enc.go
encoders/builtin/json_enc.go
encoders/protobuf/protobuf_enc.go
encoders/protobuf/testdata/pbtest.pb.go
jetstream/api.go
js.go
micro/request.go
micro/service.go
micro/test/service_test.go
nats_test.go
netchan.go
test/helper_test.go
test/js_test.go
test/json_test.go
test/protobuf_test.go

This reverts change from #1315 before a patch release and will be added again after the release.

Revert "[IMPROVED] Replace empty interface with any"

---

jetstream/consumer_config.go
jetstream/ordered.go

[ADDED] HeadersOnly field on OrderedConsumerConfig

---

.travis.yml
go_test.mod
go_test.sum

Upgrades default `go_test.mod` version for testing too.

Adds nats-server dev + main branches to CI testing

---

jetstream/README.md

Fixes to jetstream/readme

---

nats.go

style: show unlimited reconnection usage at the comments

---

README.md
nats.go

With this release, Object Store is out of experimental preview. Additionally, `jetstream` package now supports KeyValue stores. Object store will be added to `jetstream` in future release.
- JetStream:
- KeyValue is now available as part of the new JetStream API (#1362)
- KeyValue:
- `UpdatesOnly` option for KV watchers (#1378)
- ObjectStore:
- `UpdatesOnly` option for object store watchers (#1377)
- Core NATS:
- Invoke `ErrorHandler()` on preparing connection string when reconnecting (#1397)
- Fixed several flaky tests (#1374, #1380)
- Improve comment on `MaxReconnects` (#1394)
- Typos in comments and error messages across the code base (#1381)
- JetStream:
- Fix typo in doc comment for SkipConsumerLookup (#1355)
- Remove doubled error handling (#1387)
- ObjectStore:
- Added client …

Release v1.29.0

---

micro/README.md
micro/service.go
micro/test/service_test.go

Addresses ADR-32 changes from https://github.com/nats-io/nats-architecture-and-design/pull/239

[ADDED] Customizing queue groups in micro

---

jetstream/consumer.go
jetstream/ordered.go
js.go

[FIXED] Panic on ConsumerInfo when empty reponse and errors are returned

---

dependencies.md

Update client dependencies list

---

bench/bench.go
context.go
enc.go
encoders/builtin/default_enc.go
encoders/builtin/gob_enc.go
encoders/builtin/json_enc.go
encoders/protobuf/protobuf_enc.go
example_test.go
examples/nats-bench/main.go
internal/parser/parse_test.go
jserrors.go
jsm.go
kv.go
micro/example_package_test.go
netchan.go
object.go
test/basic_test.go
test/cluster_test.go
test/drain_test.go
test/headers_test.go
test/json_test.go
test/object_test.go
test/protobuf_test.go
test/reconnect_test.go
test/sub_test.go

Update dates in licence headers

---

README.md

Add nats by example link

---

jetstream/ordered.go
jetstream/test/ordered_test.go

Fix ordered consumer Next timeout

---

go.mod
go.sum

Bump nkeys version

---

jetstream/jetstream_options.go
jsm.go

[IMPROVED] AddConsumer documentation

---

jetstream/README.md

[IMPROVED] Missing section in jetstream readme ToC

---

micro/service.go

Fix invalid stopErr that makes line 638 never reached. 
Signed-off-by: Ramon Berrutti [ramonberrutti@gmail.com](mailto:ramonberrutti@gmail.com)

[FIXED] Incorrect stopErr used

---

README.md
nats.go

- Core NATS:
- `StatusChanged` method for subscription event notifications (#1570)
- Object Store:
- Add missing `Compression` struct tag (#1559)
- `Fetch` and `FetchBatch` will no longer publish a pull request if the subscription is closed or draining (#1582)
- Object Store:
- Bind Object Store bucket stream when getting object (#1568, #1578)
- Add testing section and format `CONTRIBUTING.md`(#1574)
- Improved performance of `respToken` in muxer (#1575)
- Fixed typos in comments (#1581)

Release v1.34.0

---

README.md
nats.go

- JetStream:
-  Fixed async publish error handling on disconnect (#1592)
-  Fixed race condition in `Fetch` and `FetchBatch` when using heartbeats (#1601)

Release v1.34.1

---

README.md

[IMPROVED] Add note to readme about backwards compatibility

---

jetstream/errors.go
jetstream/jetstream.go
jserrors.go
jsm.go

[IMPROVED] Documentation for AccountInfo and ErrJetStreamNotEnabled

---

jetstream/README.md

Small improvements to the example code

Small improvement to example code in jetstream/README.md

---

jsm.go

Enhanced documentation by adding a description for the StreamConfig struct in jsm.go

Added description for the StreamConfig struct in jsm.go

---

README.md
nats.go

- Service API:
- Added API to read reply subject from `micro.Request` (#1589)
- Core NATS:
- Added `ForceReconnect` method on connection for manually triggering reconnect (#1624)
- KeyValue:
- Fixed invalid `DiscardPolicy` being set when creating a new KeyValue store using the `jetstream` package. Previously created KV instances will be auto-repaired when calling `CreateKeyValue` (#1616, #1617)
- JetStream:
- Fixed validation for streams, consumers and KV buckets to avoid protocol errors (#1613)
- Core NATS:
- Fixed `ConnectedCB` not being invoked when using `RetryOnFailedConnect: true` and the initial `nats.Connect` fails (#1619)
- Core NATS:
- Remove unnecessary allocations from `readMIMEHeader` (#1609)
- KeyValue:
- Added json tags to KeyValueConfig struct (#1630)
- …

Release v1.35.0

---

jetstream/jetstream.go
jetstream/ordered.go
jetstream/stream.go
jetstream/test/ordered_test.go

[FIXED] Set OptStartSeq correctly in OrderedConsumerConfig

---

README.md
nats.go

- JetStream:
- Set `OptStartSeq` correctly in `OrderedConsumerConfig` and simplify ordered consumer creation (#1644, #1645)
- Fix invalid handling of mismatched sequence when using `Messages()` for ordered consumer (#1646)
- JetStream:
- Remove `ConsumerInfo()` calls in `Consume()` and `Messages()` after reconnect (#1643)
- Fixed compatibility tests (#1637)
- Fixed comment typos (#1638, #1639)

Release v1.36.0

---

test/configs/docker/Dockerfile

Update docker for compatibility tests

---

README.md

Correct README.md formatting

---

jetstream/errors.go
jetstream/jetstream.go
jetstream/publish.go
jetstream/test/jetstream_test.go
js.go
jserrors.go
test/js_test.go

[ADDED] CleanupPublisher method for removing internal JetStream subscription

---

jetstream/test/jetstream_test.go
test/cluster_test.go
test/js_test.go
ws.go

Fix linter issues

---

micro/README.md

[FIXED] Invalid response schema in README for Service API

---

js.go

Signed-off-by: Piotr Piotrowski piotr@synadia.com

[FIXED] Add missing nats prefix to error

---

jetstream/object.go

Currently `DeleteObjectStore` incorrectly returns `ErrStreamNotFound` if the Object Store Bucket is not found

Correct Error Returned from DeleteObjectStore

---

micro/service.go

Remove stale experimental comment

---

js.go
test/js_test.go

Previously when using `nats.Context(ctx)` option in `js.Subscribe()`, `ctx` was not used when creating consumer.

[FIXED] Set context from option when creating consumer in js.Subscribe

---

nats.go

[FIXED] Data race when reading current status in sub.StatusChanged and nc.StatusChanged

---

jetstream/kv.go
jetstream/object.go
jetstream/test/kv_test.go
jetstream/test/object_test.go
object.go
test/kv_test.go
test/object_test.go

[FIXED] Ensure object watcher stop closes the updates channel

---

kv.go

[FIXED] Use context in when purging stream in kv.PurgeDeletes()

---

README.md
nats.go

- Core NATS:
- Add `nc.RemoveStatusListener()` method (#1856)
- Fix `Fetch` and `FetchBatch` memory leak (#1856)
- Legacy KeyValue:
- Use context in when purging stream in `kv.PurgeDeletes()` (#1858)
- Bump golang.org/x/crypto to fix vulnerability (#1857)

Release v1.41.2

---

README.md
nats.go

This release adds per-key TTL functionality to key-value stores. It adds:
1. `LimitMarkerTTL` config option to enable automatic tombstone deletion.
2. `KeyTTL` option to `kv.Create()`
3. `PurgeTTL()` option to `kv.Purge()`
- KeyValue:
- Added KeyValue per key TTL support and limit markers (#1864)

Release v1.42.0

---

jetstream/ordered.go
jetstream/test/ordered_test.go

Ordered consumers were not properly closing when the underlying connection was closed.

[FIXED] Ordered consumer not closing on connection close

---

nats.go

[FIXED] Clear status listeners map on SubscriptionClosed event

---

jetstream/consumer.go
jetstream/errors.go
jserrors.go
jsm.go

[FIXED] Handle empty response when creating a consumer

---

jetstream/consumer.go
jetstream/errors.go

Add ErrMaximumConsumersLimit, his JS API code and handling on upsertConsumer.
Also add JS API err codes sorting by numeric values as code reading improvement

[UPDATED] Add max consumers limit error (code=10026)

---

go_test.mod
go_test.sum
jetstream/consumer_config.go
jetstream/jetstream_options.go
jetstream/pull.go
jetstream/test/consumer_test.go

[ADDED] Prioritized priority policy

---

jetstream/test/jetstream_test.go

[IMPROVED] Add test veryfying if mirror can be updated to regular stream

---

jetstream/stream_config.go

[ADDED] AllowAtomicPublish option on stream config 

---

jetstream/kv.go
jetstream/test/kv_test.go

[ADDED] Add Metadata support to KeyValue buckets

---

jetstream/stream_config.go

[FIXED] Add omitempty to AllowMsgTTL and AllowMsgCounter
